import type { StoreId } from "@/types/store";
import {
  formatCurrencyCompact,
  formatPercentChange,
  formatPercentDelta,
} from "@/lib/format/number";

/**
 * National-level "strategic" insights derived from country-wide aggregates.
 * Unlike Gerente/Supervisor coaching insights (which target individuals),
 * Admin insights are framed as C-level observations: value created,
 * opportunity gaps, brand strategy. Severity is always "info" — they're
 * board-room reads, not alerts.
 */

export type StrategicIcon = "trending-up" | "target" | "compass";

export interface StrategicInsight {
  severity: "info";
  icon: StrategicIcon;
  title: string;
  description: string;
}

export interface StoreSnapshotForInsights {
  storeId: StoreId;
  storeName: string;
  sales: number;
  /** Reco→purchase rate, 0-100. */
  convReco: number;
}

export interface StrategicInsightsInput {
  nationalSales: number;
  /** Average reco→purchase rate across the country, 0-100. */
  nationalAvgConvReco: number;
  /** Average ticket — used to translate "extra recommendations" into money. */
  nationalAvgTicket: number;
  /** Total number of recommendations issued in the period. */
  totalRecommendations: number;
  stores: readonly StoreSnapshotForInsights[];
  /** Period-over-period growth % per brand. */
  brandGrowth: { lancome: number; ysl: number };
}

/** Up to 3 insights. Returned in display order. */
export function computeStrategicInsights(
  input: StrategicInsightsInput,
): StrategicInsight[] {
  const out: StrategicInsight[] = [];

  // 1. Value generated by clienteling = recos converted × avg ticket.
  const convertedByClienteling =
    input.totalRecommendations * (input.nationalAvgConvReco / 100);
  const clientelingValue = Math.round(
    convertedByClienteling * input.nationalAvgTicket,
  );
  if (clientelingValue > 0) {
    out.push({
      severity: "info",
      icon: "trending-up",
      title: `El clienteling generó ${formatCurrencyCompact(clientelingValue)} adicionales este mes`,
      description:
        "vs. benchmark sin clienteling (ventas sin recomendaciones registradas).",
    });
  }

  // 2. Opportunity gap: best store conv vs national avg.
  if (input.stores.length > 0 && input.nationalAvgConvReco > 0) {
    const best = [...input.stores].sort((a, b) => b.convReco - a.convReco)[0];
    if (best && best.convReco > input.nationalAvgConvReco * 1.2) {
      const gapPp = best.convReco - input.nationalAvgConvReco;
      const gapAmount = Math.round(
        (gapPp / 100) * input.nationalSales,
      );
      out.push({
        severity: "info",
        icon: "target",
        title: `Si todo el país tuviera la conversión de ${best.storeName}, generaría ${formatCurrencyCompact(gapAmount)} adicionales`,
        description: `${best.storeName} convierte ${formatPercentDelta(gapPp)} por encima del promedio nacional.`,
      });
    }
  }

  // 3. Brand strategy gap.
  const diffPp = input.brandGrowth.lancome - input.brandGrowth.ysl;
  if (Math.abs(diffPp) > 5) {
    const lcmAhead = diffPp > 0;
    const winner = lcmAhead ? "Lancôme" : "YSL";
    const loser = lcmAhead ? "YSL" : "Lancôme";
    const winnerGrowth = lcmAhead
      ? input.brandGrowth.lancome
      : input.brandGrowth.ysl;
    const loserGrowth = lcmAhead
      ? input.brandGrowth.ysl
      : input.brandGrowth.lancome;
    out.push({
      severity: "info",
      icon: "compass",
      title: `${winner} creció ${formatPercentChange(winnerGrowth)} vs ${loser} ${formatPercentChange(loserGrowth)} este mes`,
      description: `Considera revisar estrategia comercial ${loser} para el próximo trimestre.`,
    });
  }

  return out.slice(0, 3);
}
