import "server-only";
import type { Client, ClientId } from "@/types/client";
import type { Interaction } from "@/types/interaction";
import type { Purchase } from "@/types/purchase";
import type { Sample } from "@/types/sample";
import type { Recommendation } from "@/types/recommendation";
import type { Consent } from "@/types/consent";
import type { Communication, CommunicationId } from "@/types/communication";
import type { StaffId } from "@/types/staff";
import type { StoreId } from "@/types/store";
import type { Sku } from "@/types/product";

/**
 * Seeds for the multi-tienda + multi-marca scope (RF-52..RF-54, RNF-13/14).
 *
 * Distribution by store (5 clientas each, mix of brand assignment):
 *
 *   Polanco  (st-pol) — 5 clientas: 2 multi-brand · 2 LCM-only · 1 YSL-only
 *   Perisur  (st-per) — 5 clientas: 2 multi-brand · 1 LCM-only · 2 YSL-only
 *   Santa Fe (st-stf) — 5 clientas: 2 multi-brand · 2 LCM-only · 1 YSL-only
 *
 * Client first names are deliberately disjoint from staff first names
 * (Valentina, Fernanda, Daniela, etc.) to avoid demo confusion.
 *
 * Multi-brand clientas appear in BOTH brand BAs' lists per Option A
 * (intersection). The same clienta can have a Lancôme purchase (by a LCM BA)
 * AND a YSL purchase (by a YSL BA) — same record, two attributions.
 */

const ST_POL = "st-pol" as StoreId;
const ST_PER = "st-per" as StoreId;
const ST_STF = "st-stf" as StoreId;

// Staff IDs — match user.repository.ts seed
const BA_POL_LCM_1 = "us-ba-pol-lcm-1" as StaffId; // Valentina Ríos
const BA_POL_LCM_2 = "us-ba-pol-lcm-2" as StaffId; // Fernanda Oliveros
const BA_POL_YSL_1 = "us-ba-pol-ysl-1" as StaffId; // Daniela Castro
const BA_POL_YSL_2 = "us-ba-pol-ysl-2" as StaffId; // Sofía Marín
const BA_PER_LCM_1 = "us-ba-per-lcm-1" as StaffId; // Regina Mendoza
const BA_PER_LCM_2 = "us-ba-per-lcm-2" as StaffId; // Andrea Lozano
const BA_PER_YSL_1 = "us-ba-per-ysl-1" as StaffId; // Lucía Cabrera
const BA_PER_YSL_2 = "us-ba-per-ysl-2" as StaffId; // Mariana Esquivel
const BA_STF_LCM_1 = "us-ba-stf-lcm-1" as StaffId; // Renata Salazar
const BA_STF_LCM_2 = "us-ba-stf-lcm-2" as StaffId; // Ximena Pereda
const BA_STF_YSL_1 = "us-ba-stf-ysl-1" as StaffId; // Paulina Treviño
const BA_STF_YSL_2 = "us-ba-stf-ysl-2" as StaffId; // Carolina Andrade

export const SEED_CLIENTS: Client[] = [
  // ── Polanco (st-pol) — 5 clientas ─────────────────────────────────────────
  {
    id: "cl-constanza" as ClientId,
    name: "Constanza Iturbide",
    phone: "5512345678",
    email: "constanza.iturbide@example.mx",
    birthday: "1988-05-22",
    city: "Ciudad de México",
    age: 37,
    preferredLang: "es-MX",
    since: "2021-03-14",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_POL,
    skin: { type: "Madura", concerns: ["Líneas finas", "Luminosidad"], tone: "Medio cálido" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 8420, toNext: 0 },
    stats: { ltv: 218_450, visits: 14, avgTicket: 15_603, lastPurchase: "2026-04-21" },
    affinities: ["Sérum antiedad", "Fragancia oriental"],
    interests: ["Skincare", "Fragancia"],
    routine: "Profesional",
  },
  {
    id: "cl-ofelia" as ClientId,
    name: "Ofelia Bastida",
    phone: "5587654321",
    email: "ofelia.bastida@example.mx",
    birthday: "1995-11-03",
    city: "Ciudad de México",
    age: 30,
    preferredLang: "es-MX",
    since: "2023-08-09",
    tier: "Icon",
    brands: ["Lancôme"],
    storeId: ST_POL,
    skin: { type: "Mixta", concerns: ["Poros", "Luminosidad"], tone: "Medio" },
    allergies: ["Fragancia ámbar"],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 3120, toNext: 1880 },
    stats: { ltv: 84_900, visits: 7, avgTicket: 12_128, lastPurchase: "2026-04-02" },
    affinities: ["Hydrating Boost"],
    interests: ["Skincare"],
    routine: "Avanzada",
  },
  {
    id: "cl-lorena" as ClientId,
    name: "Lorena Pacheco",
    phone: "5511223344",
    email: "lorena.pacheco@example.mx",
    birthday: "2000-07-09",
    city: "Ciudad de México",
    age: 25,
    preferredLang: "es-MX",
    since: "2026-02-12",
    tier: "Signature",
    brands: ["Lancôme"],
    storeId: ST_POL,
    skin: { type: "Grasa", concerns: ["Acné adulto", "Textura"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 420, toNext: 1580 },
    stats: { ltv: 4_980, visits: 1, avgTicket: 4_980, lastPurchase: "2026-03-30" },
    affinities: [],
    interests: ["Skincare"],
    routine: "Básica",
  },
  {
    id: "cl-adriana" as ClientId,
    name: "Adriana Quintero",
    phone: "5566778899",
    email: "adriana.quintero@example.mx",
    birthday: "1991-04-18",
    city: "Ciudad de México",
    age: 35,
    preferredLang: "es-MX",
    since: "2024-05-14",
    tier: "Icon",
    brands: ["YSL"],
    storeId: ST_POL,
    skin: { type: "Mixta", concerns: ["Luminosidad"], tone: "Medio claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 2700, toNext: 2300 },
    stats: { ltv: 38_400, visits: 3, avgTicket: 12_800, lastPurchase: "2026-03-18" },
    affinities: ["Libre", "All Hours"],
    interests: ["Maquillaje", "Fragancia"],
    routine: "Intermedia",
  },
  {
    id: "cl-beatriz" as ClientId,
    name: "Beatriz Galván",
    phone: "5599887766",
    email: "beatriz.galvan@example.mx",
    birthday: "1985-10-30",
    city: "Ciudad de México",
    age: 40,
    preferredLang: "es-MX",
    since: "2020-01-22",
    tier: "Signature",
    brands: ["Lancôme", "YSL"],
    storeId: ST_POL,
    skin: { type: "Normal", concerns: ["Luminosidad"], tone: "Oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 1820, toNext: 180 },
    stats: { ltv: 22_400, visits: 3, avgTicket: 7_467, lastPurchase: "2026-01-04" },
    affinities: ["Génifique", "Touche Éclat"],
    interests: ["Skincare", "Maquillaje", "Fragancia"],
    routine: "Intermedia",
  },

  // ── Perisur (st-per) — 5 clientas ─────────────────────────────────────────
  {
    id: "cl-cristina" as ClientId,
    name: "Cristina Mendieta",
    phone: "5544556677",
    email: "cristina.mendieta@example.mx",
    birthday: "1992-02-14",
    city: "Ciudad de México",
    age: 33,
    preferredLang: "es-MX",
    since: "2022-06-01",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_PER,
    skin: { type: "Seca", concerns: ["Hidratación", "Sensibilidad"], tone: "Claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 7600, toNext: 0 },
    stats: { ltv: 186_200, visits: 11, avgTicket: 16_927, lastPurchase: "2026-04-25" },
    affinities: ["Absolue", "Y Eau de Parfum"],
    interests: ["Skincare", "Fragancia"],
    routine: "Profesional",
  },
  {
    id: "cl-elena" as ClientId,
    name: "Elena Bermúdez",
    phone: "5523456789",
    email: "elena.bermudez@example.mx",
    birthday: "1986-08-27",
    city: "Ciudad de México",
    age: 39,
    preferredLang: "es-MX",
    since: "2020-11-04",
    tier: "Icon",
    brands: ["Lancôme"],
    storeId: ST_PER,
    skin: { type: "Madura", concerns: ["Firmeza", "Manchas"], tone: "Medio oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 3540, toNext: 1460 },
    stats: { ltv: 72_100, visits: 6, avgTicket: 12_017, lastPurchase: "2026-03-10" },
    affinities: ["Génifique"],
    interests: ["Skincare"],
    routine: "Avanzada",
  },
  {
    id: "cl-gabriela" as ClientId,
    name: "Gabriela Esparza",
    phone: "5534567890",
    email: "gabriela.esparza@example.mx",
    birthday: "1990-12-05",
    city: "Ciudad de México",
    age: 35,
    preferredLang: "es-MX",
    since: "2023-03-20",
    tier: "Icon",
    brands: ["YSL"],
    storeId: ST_PER,
    skin: { type: "Normal", concerns: ["Luminosidad"], tone: "Medio" },
    allergies: ["Niacinamida"],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 2120, toNext: 2880 },
    stats: { ltv: 28_900, visits: 3, avgTicket: 9_633, lastPurchase: "2026-04-12" },
    affinities: ["Libre", "All Hours"],
    interests: ["Maquillaje", "Fragancia"],
    routine: "Avanzada",
  },
  {
    id: "cl-ines" as ClientId,
    name: "Inés Villaseñor",
    phone: "5545678901",
    email: "ines.villasenor@example.mx",
    birthday: "1998-06-11",
    city: "Ciudad de México",
    age: 27,
    preferredLang: "es-MX",
    since: "2026-01-09",
    tier: "Signature",
    brands: ["YSL"],
    storeId: ST_PER,
    skin: { type: "Mixta", concerns: ["Poros"], tone: "Claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 380, toNext: 1620 },
    stats: { ltv: 3_800, visits: 1, avgTicket: 3_800, lastPurchase: "2026-04-12" },
    affinities: [],
    interests: ["Maquillaje"],
    routine: "Básica",
  },
  {
    id: "cl-julieta" as ClientId,
    name: "Julieta Cabello",
    phone: "5556789012",
    email: "julieta.cabello@example.mx",
    birthday: "1994-09-23",
    city: "Ciudad de México",
    age: 31,
    preferredLang: "es-MX",
    since: "2024-08-15",
    tier: "Signature",
    brands: ["Lancôme", "YSL"],
    storeId: ST_PER,
    skin: { type: "Sensible", concerns: ["Sensibilidad", "Hidratación"], tone: "Claro" },
    allergies: ["Retinol"],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 1280, toNext: 720 },
    stats: { ltv: 14_600, visits: 2, avgTicket: 7_300, lastPurchase: "2026-02-22" },
    affinities: ["Hydrating Boost"],
    interests: ["Skincare", "Maquillaje"],
    routine: "Intermedia",
  },

  // ── Santa Fe (st-stf) — 5 clientas ────────────────────────────────────────
  {
    id: "cl-karla" as ClientId,
    name: "Karla Aguilar",
    phone: "5567890123",
    email: "karla.aguilar@example.mx",
    birthday: "1987-01-29",
    city: "Ciudad de México",
    age: 39,
    preferredLang: "es-MX",
    since: "2022-02-17",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_STF,
    skin: { type: "Mixta", concerns: ["Líneas finas", "Manchas"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 9120, toNext: 0 },
    stats: { ltv: 245_800, visits: 16, avgTicket: 15_363, lastPurchase: "2026-04-28" },
    affinities: ["Absolue Soft Cream", "Black Opium"],
    interests: ["Skincare", "Maquillaje", "Fragancia"],
    routine: "Profesional",
  },
  {
    id: "cl-marina" as ClientId,
    name: "Marina Becerra",
    phone: "5578901234",
    email: "marina.becerra@example.mx",
    birthday: "1983-03-14",
    city: "Ciudad de México",
    age: 43,
    preferredLang: "es-MX",
    since: "2019-09-08",
    tier: "Icon",
    brands: ["Lancôme"],
    storeId: ST_STF,
    skin: { type: "Madura", concerns: ["Firmeza", "Luminosidad"], tone: "Medio oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 4360, toNext: 640 },
    stats: { ltv: 91_200, visits: 8, avgTicket: 11_400, lastPurchase: "2026-04-18" },
    affinities: ["Absolue", "Génifique"],
    interests: ["Skincare", "Maquillaje"],
    routine: "Avanzada",
  },
  {
    id: "cl-nadia" as ClientId,
    name: "Nadia Hinojosa",
    phone: "5589012345",
    email: "nadia.hinojosa@example.mx",
    birthday: "1996-11-19",
    city: "Ciudad de México",
    age: 29,
    preferredLang: "es-MX",
    since: "2024-04-04",
    tier: "Icon",
    brands: ["YSL"],
    storeId: ST_STF,
    skin: { type: "Grasa", concerns: ["Acné adulto", "Poros"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 2890, toNext: 2110 },
    stats: { ltv: 28_700, visits: 3, avgTicket: 9_567, lastPurchase: "2025-12-10" },
    affinities: ["All Hours", "Touche Éclat"],
    interests: ["Maquillaje"],
    routine: "Intermedia",
  },
  {
    id: "cl-pamela" as ClientId,
    name: "Pamela Vázquez",
    phone: "5590123456",
    email: "pamela.vazquez@example.mx",
    birthday: "1999-05-08",
    city: "Ciudad de México",
    age: 26,
    preferredLang: "es-MX",
    since: "2025-11-21",
    tier: "Signature",
    brands: ["Lancôme"],
    storeId: ST_STF,
    skin: { type: "Seca", concerns: ["Hidratación"], tone: "Claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 560, toNext: 1440 },
    stats: { ltv: 5_640, visits: 1, avgTicket: 5_640, lastPurchase: "2026-02-08" },
    affinities: [],
    interests: ["Skincare"],
    routine: "Básica",
  },
  {
    id: "cl-rocio" as ClientId,
    name: "Rocío Castañeda",
    phone: "5501234567",
    email: "rocio.castaneda@example.mx",
    birthday: "1989-07-02",
    city: "Ciudad de México",
    age: 36,
    preferredLang: "es-MX",
    since: "2023-10-30",
    tier: "Signature",
    brands: ["Lancôme", "YSL"],
    storeId: ST_STF,
    skin: { type: "Normal", concerns: ["Luminosidad"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 1740, toNext: 260 },
    stats: { ltv: 18_900, visits: 2, avgTicket: 9_450, lastPurchase: "2026-01-25" },
    affinities: ["Libre"],
    interests: ["Fragancia"],
    routine: "Intermedia",
  },
];

export const SEED_PURCHASES: Purchase[] = [
  // ── Polanco ───────────────────────────────────────────────────────────────
  // Constanza (multi-brand) gets a LCM purchase by BA Lancôme...
  {
    id: "pu-1" as Purchase["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    storeId: ST_POL,
    at: "2026-04-21T18:32:00.000Z",
    items: [
      { sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 9_800 },
      { sku: "LC-GEN-50" as Sku, qty: 1, unitPrice: 6_400 },
    ],
    total: 16_200,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260421-0892",
  },
  // ...and a separate YSL purchase by BA YSL (Option A in action).
  {
    id: "pu-2" as Purchase["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_YSL_1,
    storeId: ST_POL,
    at: "2026-03-12T15:10:00.000Z",
    items: [{ sku: "YS-LIB-50" as Sku, qty: 1, unitPrice: 8_900 }],
    total: 8_900,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260312-0421",
  },
  {
    id: "pu-3" as Purchase["id"],
    clientId: "cl-ofelia" as ClientId,
    baId: BA_POL_LCM_2,
    storeId: ST_POL,
    at: "2026-04-02T16:11:00.000Z",
    items: [{ sku: "LC-HYB-30" as Sku, qty: 1, unitPrice: 12_100 }],
    total: 12_100,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260402-0145",
  },
  {
    id: "pu-4" as Purchase["id"],
    clientId: "cl-adriana" as ClientId,
    baId: BA_POL_YSL_2,
    storeId: ST_POL,
    at: "2026-03-18T15:45:00.000Z",
    items: [{ sku: "YS-LIB-50" as Sku, qty: 1, unitPrice: 8_900 }],
    total: 8_900,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260318-0312",
  },

  // ── Perisur ───────────────────────────────────────────────────────────────
  {
    id: "pu-5" as Purchase["id"],
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    storeId: ST_PER,
    at: "2026-04-25T17:00:00.000Z",
    items: [{ sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 9_800 }],
    total: 9_800,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260425-0118",
  },
  {
    id: "pu-6" as Purchase["id"],
    clientId: "cl-elena" as ClientId,
    baId: BA_PER_LCM_2,
    storeId: ST_PER,
    at: "2026-03-10T11:20:00.000Z",
    items: [{ sku: "LC-GEN-50" as Sku, qty: 1, unitPrice: 6_400 }],
    total: 6_400,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260310-0207",
  },
  {
    id: "pu-7" as Purchase["id"],
    clientId: "cl-ines" as ClientId,
    baId: BA_PER_YSL_2,
    storeId: ST_PER,
    at: "2026-04-12T19:05:00.000Z",
    items: [{ sku: "YS-RPC-01" as Sku, qty: 4, unitPrice: 950 }],
    total: 3_800,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260412-0498",
  },
  {
    id: "pu-8" as Purchase["id"],
    clientId: "cl-julieta" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    at: "2026-02-22T13:25:00.000Z",
    items: [{ sku: "YS-OR-100" as Sku, qty: 1, unitPrice: 6_490 }],
    total: 6_490,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260222-0061",
  },

  // ── Santa Fe ──────────────────────────────────────────────────────────────
  {
    id: "pu-9" as Purchase["id"],
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_LCM_1,
    storeId: ST_STF,
    at: "2026-04-28T16:30:00.000Z",
    items: [
      { sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 9_800 },
      { sku: "LC-HYB-30" as Sku, qty: 1, unitPrice: 12_100 },
    ],
    total: 21_900,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "PH-260428-0931",
  },
  {
    id: "pu-10" as Purchase["id"],
    clientId: "cl-marina" as ClientId,
    baId: BA_STF_LCM_2,
    storeId: ST_STF,
    at: "2026-04-18T14:15:00.000Z",
    items: [{ sku: "LC-GEN-50" as Sku, qty: 1, unitPrice: 6_400 }],
    total: 6_400,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "PH-260418-0577",
  },
  {
    id: "pu-11" as Purchase["id"],
    clientId: "cl-nadia" as ClientId,
    baId: BA_STF_YSL_1,
    storeId: ST_STF,
    at: "2025-12-10T18:00:00.000Z",
    items: [{ sku: "YS-OR-100" as Sku, qty: 1, unitPrice: 6_490 }],
    total: 6_490,
    payment: "card",
    brand: "YSL",
    ticketRef: "PH-251210-0188",
  },
  {
    id: "pu-12" as Purchase["id"],
    clientId: "cl-rocio" as ClientId,
    baId: BA_STF_YSL_2,
    storeId: ST_STF,
    at: "2026-01-25T18:00:00.000Z",
    items: [{ sku: "YS-LIB-50" as Sku, qty: 1, unitPrice: 8_900 }],
    total: 8_900,
    payment: "card",
    brand: "YSL",
    ticketRef: "PH-260125-0244",
  },
];

export const SEED_INTERACTIONS: Interaction[] = [
  {
    id: "int-1" as Interaction["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    brand: "Lancôme",
    kind: "purchase",
    at: "2026-04-21T18:32:00.000Z",
    amount: 16_200,
  },
  {
    id: "int-2" as Interaction["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_YSL_1,
    brand: "YSL",
    kind: "consultation",
    at: "2026-03-15T15:00:00.000Z",
    durationMin: 45,
    notes: "Renovó descubrimiento Or Rouge; interesada en travel size.",
  },
  {
    id: "int-3" as Interaction["id"],
    clientId: "cl-ofelia" as ClientId,
    baId: BA_POL_LCM_2,
    brand: "Lancôme",
    kind: "sample",
    at: "2026-04-08T14:20:00.000Z",
    notes: "Muestra Hydrating Boost 7d.",
  },
];

export const SEED_SAMPLES: Sample[] = [
  {
    id: "sp-1" as Sample["id"],
    clientId: "cl-ofelia" as ClientId,
    baId: BA_POL_LCM_2,
    sku: "LC-HYB-7" as Sku,
    name: "Hydrating Boost · 7d",
    givenAt: "2026-04-08T14:20:00.000Z",
    followUpAt: "2026-04-22T00:00:00.000Z",
    converted: false,
  },
];

export const SEED_RECOMMENDATIONS: Recommendation[] = [
  // Polanco
  {
    id: "rc-1" as Recommendation["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    storeId: ST_POL,
    brand: "Lancôme",
    at: "2026-04-21T18:00:00.000Z",
    items: ["LC-ABS-50" as Sku, "LC-GEN-50" as Sku],
    status: "converted",
    purchaseId: "pu-1" as Purchase["id"],
  },
  {
    id: "rc-2" as Recommendation["id"],
    clientId: "cl-adriana" as ClientId,
    baId: BA_POL_YSL_2,
    storeId: ST_POL,
    brand: "YSL",
    at: "2026-03-18T15:30:00.000Z",
    items: ["YS-LIB-50" as Sku],
    status: "converted",
    purchaseId: "pu-4" as Purchase["id"],
  },
  // Perisur
  {
    id: "rc-3" as Recommendation["id"],
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    storeId: ST_PER,
    brand: "Lancôme",
    at: "2026-04-25T16:30:00.000Z",
    items: ["LC-ABS-50" as Sku],
    status: "converted",
    purchaseId: "pu-5" as Purchase["id"],
  },
  {
    id: "rc-4" as Recommendation["id"],
    clientId: "cl-gabriela" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    brand: "YSL",
    at: "2026-03-09T15:10:00.000Z",
    items: ["YS-RPC-01" as Sku],
    status: "pending",
  },
  // Santa Fe
  {
    id: "rc-5" as Recommendation["id"],
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_LCM_1,
    storeId: ST_STF,
    brand: "Lancôme",
    at: "2026-04-28T16:00:00.000Z",
    items: ["LC-ABS-50" as Sku, "LC-HYB-30" as Sku],
    status: "converted",
    purchaseId: "pu-9" as Purchase["id"],
  },
  {
    id: "rc-6" as Recommendation["id"],
    clientId: "cl-nadia" as ClientId,
    baId: BA_STF_YSL_1,
    storeId: ST_STF,
    brand: "YSL",
    at: "2025-12-09T11:30:00.000Z",
    items: ["YS-RPC-01" as Sku],
    status: "pending",
  },
];

export const SEED_COMMUNICATIONS: Communication[] = [
  // ── Polanco ───────────────────────────────────────────────────────────────
  {
    id: "cm-1" as CommunicationId,
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    brand: "Lancôme",
    storeId: ST_POL,
    channel: "WhatsApp",
    direction: "outbound",
    at: "2026-04-22T14:32:00.000Z",
    templateId: "tpl-postvisit-es",
    body: "Hola Constanza, ¿cómo te sentiste con el sérum Génifique?",
    status: "read",
  },
  {
    id: "cm-2" as CommunicationId,
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    brand: "Lancôme",
    storeId: ST_POL,
    channel: "WhatsApp",
    direction: "inbound",
    at: "2026-04-22T18:04:00.000Z",
    body: "¡Increíble, notó mi marido el brillo!",
    status: "read",
  },
  {
    id: "cm-3" as CommunicationId,
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_YSL_1,
    brand: "YSL",
    storeId: ST_POL,
    channel: "Email",
    direction: "outbound",
    at: "2026-03-13T09:00:00.000Z",
    templateId: "tpl-launch-es",
    body: "Hola Constanza, la nueva Libre Le Parfum acaba de llegar.",
    status: "delivered",
  },
  {
    id: "cm-4" as CommunicationId,
    clientId: "cl-ofelia" as ClientId,
    baId: BA_POL_LCM_2,
    brand: "Lancôme",
    storeId: ST_POL,
    channel: "SMS",
    direction: "outbound",
    at: "2026-04-20T11:00:00.000Z",
    templateId: "tpl-replenish-es",
    body: "Tu Hydrating Boost está por terminarse…",
    status: "read",
  },

  // ── Perisur ───────────────────────────────────────────────────────────────
  {
    id: "cm-5" as CommunicationId,
    clientId: "cl-gabriela" as ClientId,
    baId: BA_PER_YSL_1,
    brand: "YSL",
    storeId: ST_PER,
    channel: "WhatsApp",
    direction: "outbound",
    at: "2026-04-15T10:00:00.000Z",
    templateId: "tpl-launch-es",
    body: "Gabriela, acaba de llegar Libre Le Parfum Intense.",
    status: "delivered",
  },
  {
    id: "cm-6" as CommunicationId,
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    brand: "Lancôme",
    storeId: ST_PER,
    channel: "Email",
    direction: "outbound",
    at: "2026-04-26T10:30:00.000Z",
    templateId: "tpl-postvisit-es",
    body: "Cristina, qué bueno verte. Gracias por tu compra.",
    status: "read",
  },
  {
    id: "cm-7" as CommunicationId,
    clientId: "cl-julieta" as ClientId,
    baId: BA_PER_YSL_1,
    brand: "YSL",
    storeId: ST_PER,
    channel: "WhatsApp",
    direction: "outbound",
    at: "2026-03-01T13:00:00.000Z",
    body: "Te envío la rutina sensible que platicamos.",
    status: "read",
  },

  // ── Santa Fe ──────────────────────────────────────────────────────────────
  {
    id: "cm-8" as CommunicationId,
    clientId: "cl-marina" as ClientId,
    baId: BA_STF_LCM_1,
    brand: "Lancôme",
    storeId: ST_STF,
    channel: "WhatsApp",
    direction: "outbound",
    at: "2026-04-19T09:30:00.000Z",
    templateId: "tpl-postvisit-es",
    body: "Marina, gracias por venir. Te mando link del sérum.",
    status: "read",
  },
  {
    id: "cm-9" as CommunicationId,
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_LCM_1,
    brand: "Lancôme",
    storeId: ST_STF,
    channel: "Email",
    direction: "outbound",
    at: "2026-04-29T11:00:00.000Z",
    templateId: "tpl-anniversary-es",
    body: "Karla, queremos celebrar 7 años contigo.",
    status: "delivered",
  },
  {
    id: "cm-10" as CommunicationId,
    clientId: "cl-rocio" as ClientId,
    baId: BA_STF_YSL_2,
    brand: "YSL",
    storeId: ST_STF,
    channel: "SMS",
    direction: "outbound",
    at: "2026-02-01T10:00:00.000Z",
    templateId: "tpl-replenish-es",
    body: "Tu Libre está por terminarse. ¿Te lo aparto?",
    status: "delivered",
  },
];

export const SEED_CONSENTS: Consent[] = [
  {
    id: "co-1" as Consent["id"],
    clientId: "cl-constanza" as ClientId,
    channel: "WhatsApp",
    status: "granted",
    at: "2025-10-01T00:00:00.000Z",
    version: "v2026.03",
    source: "in-store",
  },
  {
    id: "co-2" as Consent["id"],
    clientId: "cl-constanza" as ClientId,
    channel: "Email",
    status: "granted",
    at: "2025-10-01T00:00:00.000Z",
    version: "v2026.03",
    source: "in-store",
  },
];
