import "server-only";
import type { Client, ClientId } from "@/types/client";
import type { Interaction } from "@/types/interaction";
import type { Purchase } from "@/types/purchase";
import type { Sample } from "@/types/sample";
import type { Recommendation } from "@/types/recommendation";
import type { Consent } from "@/types/consent";
import type { Communication, CommunicationId } from "@/types/communication";
import type { StaffId } from "@/types/staff";
import type { StoreId } from "@/types/store";
import type { Sku } from "@/types/product";

/**
 * Seeds for the multi-tienda + multi-marca scope (RF-52..RF-54, RNF-13/14).
 *
 * Distribution by store (5 clientas each, mix of brand assignment):
 *
 *   Polanco  (st-pol) — 5 clientas: 2 multi-brand · 2 LCM-only · 1 YSL-only
 *   Perisur  (st-per) — 5 clientas: 2 multi-brand · 1 LCM-only · 2 YSL-only
 *   Santa Fe (st-stf) — 5 clientas: 2 multi-brand · 2 LCM-only · 1 YSL-only
 *
 * Client first names are deliberately disjoint from staff first names
 * (Valentina, Fernanda, Daniela, etc.) to avoid demo confusion.
 *
 * Multi-brand clientas appear in BOTH brand BAs' lists per Option A
 * (intersection). The same clienta can have a Lancôme purchase (by a LCM BA)
 * AND a YSL purchase (by a YSL BA) — same record, two attributions.
 */

const ST_POL = "st-pol" as StoreId;
const ST_PER = "st-per" as StoreId;
const ST_STF = "st-stf" as StoreId;

// Staff IDs — match user.repository.ts seed
const BA_POL_LCM_1 = "us-ba-pol-lcm-1" as StaffId; // Valentina Ríos
const BA_POL_LCM_2 = "us-ba-pol-lcm-2" as StaffId; // Fernanda Oliveros
const BA_POL_YSL_1 = "us-ba-pol-ysl-1" as StaffId; // Daniela Castro
const BA_POL_YSL_2 = "us-ba-pol-ysl-2" as StaffId; // Sofía Marín
const BA_PER_LCM_1 = "us-ba-per-lcm-1" as StaffId; // Regina Mendoza
const BA_PER_LCM_2 = "us-ba-per-lcm-2" as StaffId; // Andrea Lozano
const BA_PER_YSL_1 = "us-ba-per-ysl-1" as StaffId; // Lucía Cabrera
const BA_PER_YSL_2 = "us-ba-per-ysl-2" as StaffId; // Mariana Esquivel
const BA_STF_LCM_1 = "us-ba-stf-lcm-1" as StaffId; // Renata Salazar
const BA_STF_LCM_2 = "us-ba-stf-lcm-2" as StaffId; // Ximena Pereda
const BA_STF_YSL_1 = "us-ba-stf-ysl-1" as StaffId; // Paulina Treviño
const BA_STF_YSL_2 = "us-ba-stf-ysl-2" as StaffId; // Carolina Andrade

export const SEED_CLIENTS: Client[] = [
  // ── Polanco (st-pol) — 5 clientas ─────────────────────────────────────────
  {
    id: "cl-constanza" as ClientId,
    name: "Constanza Iturbide",
    phone: "5512345678",
    email: "constanza.iturbide@example.mx",
    birthday: "1988-05-22",
    city: "Ciudad de México",
    age: 37,
    preferredLang: "es-MX",
    since: "2021-03-14",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_POL,
    skin: { type: "Madura", concerns: ["Líneas finas", "Luminosidad"], tone: "Medio cálido" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 8420, toNext: 0 },
    stats: { ltv: 218_450, visits: 14, avgTicket: 15_603, lastPurchase: "2026-04-21" },
    affinities: ["Sérum antiedad", "Fragancia oriental"],
    interests: ["Skincare", "Fragancia"],
    routine: "Profesional",
    createdByBaId: BA_POL_LCM_1,
    assignedBaIds: [BA_POL_LCM_1, BA_POL_YSL_1],
  },
  {
    id: "cl-ofelia" as ClientId,
    name: "Ofelia Bastida",
    phone: "5587654321",
    email: "ofelia.bastida@example.mx",
    birthday: "1995-11-03",
    city: "Ciudad de México",
    age: 30,
    preferredLang: "es-MX",
    since: "2023-08-09",
    tier: "Icon",
    brands: ["Lancôme"],
    storeId: ST_POL,
    skin: { type: "Mixta", concerns: ["Poros", "Luminosidad"], tone: "Medio" },
    allergies: ["Fragancia ámbar"],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 3120, toNext: 1880 },
    stats: { ltv: 84_900, visits: 7, avgTicket: 12_128, lastPurchase: "2026-04-02" },
    affinities: ["Hydrating Boost"],
    interests: ["Skincare"],
    routine: "Avanzada",
    createdByBaId: BA_POL_LCM_2,
    assignedBaIds: [BA_POL_LCM_2],
  },
  {
    id: "cl-lorena" as ClientId,
    name: "Lorena Pacheco",
    phone: "5511223344",
    email: "lorena.pacheco@example.mx",
    birthday: "2000-07-09",
    city: "Ciudad de México",
    age: 25,
    preferredLang: "es-MX",
    since: "2026-02-12",
    tier: "Signature",
    brands: ["Lancôme"],
    storeId: ST_POL,
    skin: { type: "Grasa", concerns: ["Acné adulto", "Textura"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 420, toNext: 1580 },
    stats: { ltv: 4_980, visits: 1, avgTicket: 4_980, lastPurchase: "2026-03-30" },
    affinities: [],
    interests: ["Skincare"],
    routine: "Básica",
    createdByBaId: BA_POL_LCM_1,
    assignedBaIds: [BA_POL_LCM_1],
  },
  {
    id: "cl-adriana" as ClientId,
    name: "Adriana Quintero",
    phone: "5566778899",
    email: "adriana.quintero@example.mx",
    birthday: "1991-04-18",
    city: "Ciudad de México",
    age: 35,
    preferredLang: "es-MX",
    since: "2024-05-14",
    tier: "Icon",
    brands: ["YSL"],
    storeId: ST_POL,
    skin: { type: "Mixta", concerns: ["Luminosidad"], tone: "Medio claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 2700, toNext: 2300 },
    stats: { ltv: 38_400, visits: 3, avgTicket: 12_800, lastPurchase: "2026-03-18" },
    affinities: ["Libre", "All Hours"],
    interests: ["Maquillaje", "Fragancia"],
    routine: "Intermedia",
    createdByBaId: BA_POL_YSL_2,
    assignedBaIds: [BA_POL_YSL_2],
  },
  {
    id: "cl-beatriz" as ClientId,
    name: "Beatriz Galván",
    phone: "5599887766",
    email: "beatriz.galvan@example.mx",
    birthday: "1985-10-30",
    city: "Ciudad de México",
    age: 40,
    preferredLang: "es-MX",
    since: "2020-01-22",
    tier: "Signature",
    brands: ["Lancôme", "YSL"],
    storeId: ST_POL,
    skin: { type: "Normal", concerns: ["Luminosidad"], tone: "Oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 1820, toNext: 180 },
    stats: { ltv: 22_400, visits: 3, avgTicket: 7_467, lastPurchase: "2026-01-04" },
    affinities: ["Génifique", "Touche Éclat"],
    interests: ["Skincare", "Maquillaje", "Fragancia"],
    routine: "Intermedia",
    createdByBaId: BA_POL_YSL_1,
    assignedBaIds: [BA_POL_YSL_1, BA_POL_LCM_1],
  },

  // ── Perisur (st-per) — 5 clientas ─────────────────────────────────────────
  {
    id: "cl-cristina" as ClientId,
    name: "Cristina Mendieta",
    phone: "5544556677",
    email: "cristina.mendieta@example.mx",
    birthday: "1992-02-14",
    city: "Ciudad de México",
    age: 33,
    preferredLang: "es-MX",
    since: "2022-06-01",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_PER,
    skin: { type: "Seca", concerns: ["Hidratación", "Sensibilidad"], tone: "Claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 7600, toNext: 0 },
    stats: { ltv: 186_200, visits: 11, avgTicket: 16_927, lastPurchase: "2026-04-25" },
    affinities: ["Absolue", "Y Eau de Parfum"],
    interests: ["Skincare", "Fragancia"],
    routine: "Profesional",
    createdByBaId: BA_PER_LCM_1,
    assignedBaIds: [BA_PER_LCM_1, BA_PER_YSL_1],
  },
  {
    id: "cl-elena" as ClientId,
    name: "Elena Bermúdez",
    phone: "5523456789",
    email: "elena.bermudez@example.mx",
    birthday: "1986-08-27",
    city: "Ciudad de México",
    age: 39,
    preferredLang: "es-MX",
    since: "2020-11-04",
    tier: "Icon",
    brands: ["Lancôme"],
    storeId: ST_PER,
    skin: { type: "Madura", concerns: ["Firmeza", "Manchas"], tone: "Medio oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 3540, toNext: 1460 },
    stats: { ltv: 72_100, visits: 6, avgTicket: 12_017, lastPurchase: "2026-03-10" },
    affinities: ["Génifique"],
    interests: ["Skincare"],
    routine: "Avanzada",
    createdByBaId: BA_PER_LCM_2,
    assignedBaIds: [BA_PER_LCM_2],
  },
  {
    id: "cl-gabriela" as ClientId,
    name: "Gabriela Esparza",
    phone: "5534567890",
    email: "gabriela.esparza@example.mx",
    birthday: "1990-12-05",
    city: "Ciudad de México",
    age: 35,
    preferredLang: "es-MX",
    since: "2023-03-20",
    tier: "Icon",
    brands: ["YSL"],
    storeId: ST_PER,
    skin: { type: "Normal", concerns: ["Luminosidad"], tone: "Medio" },
    allergies: ["Niacinamida"],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 2120, toNext: 2880 },
    stats: { ltv: 28_900, visits: 3, avgTicket: 9_633, lastPurchase: "2026-04-12" },
    affinities: ["Libre", "All Hours"],
    interests: ["Maquillaje", "Fragancia"],
    routine: "Avanzada",
    createdByBaId: BA_PER_YSL_1,
    assignedBaIds: [BA_PER_YSL_1, BA_PER_YSL_2],
  },
  {
    id: "cl-ines" as ClientId,
    name: "Inés Villaseñor",
    phone: "5545678901",
    email: "ines.villasenor@example.mx",
    birthday: "1998-06-11",
    city: "Ciudad de México",
    age: 27,
    preferredLang: "es-MX",
    since: "2026-01-09",
    tier: "Signature",
    brands: ["YSL"],
    storeId: ST_PER,
    skin: { type: "Mixta", concerns: ["Poros"], tone: "Claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 380, toNext: 1620 },
    stats: { ltv: 3_800, visits: 1, avgTicket: 3_800, lastPurchase: "2026-04-12" },
    affinities: [],
    interests: ["Maquillaje"],
    routine: "Básica",
    createdByBaId: BA_PER_YSL_2,
    assignedBaIds: [BA_PER_YSL_2],
  },
  {
    id: "cl-julieta" as ClientId,
    name: "Julieta Cabello",
    phone: "5556789012",
    email: "julieta.cabello@example.mx",
    birthday: "1994-09-23",
    city: "Ciudad de México",
    age: 31,
    preferredLang: "es-MX",
    since: "2024-08-15",
    tier: "Signature",
    brands: ["Lancôme", "YSL"],
    storeId: ST_PER,
    skin: { type: "Sensible", concerns: ["Sensibilidad", "Hidratación"], tone: "Claro" },
    allergies: ["Retinol"],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 1280, toNext: 720 },
    stats: { ltv: 14_600, visits: 2, avgTicket: 7_300, lastPurchase: "2026-02-22" },
    affinities: ["Hydrating Boost"],
    interests: ["Skincare", "Maquillaje"],
    routine: "Intermedia",
    createdByBaId: BA_PER_YSL_1,
    assignedBaIds: [BA_PER_YSL_1, BA_PER_LCM_1],
  },

  // ── Santa Fe (st-stf) — 5 clientas ────────────────────────────────────────
  {
    id: "cl-karla" as ClientId,
    name: "Karla Aguilar",
    phone: "5567890123",
    email: "karla.aguilar@example.mx",
    birthday: "1987-01-29",
    city: "Ciudad de México",
    age: 39,
    preferredLang: "es-MX",
    since: "2022-02-17",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_STF,
    skin: { type: "Mixta", concerns: ["Líneas finas", "Manchas"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 9120, toNext: 0 },
    stats: { ltv: 245_800, visits: 16, avgTicket: 15_363, lastPurchase: "2026-04-28" },
    affinities: ["Absolue Soft Cream", "Black Opium"],
    interests: ["Skincare", "Maquillaje", "Fragancia"],
    routine: "Profesional",
    createdByBaId: BA_STF_LCM_1,
    assignedBaIds: [BA_STF_LCM_1, BA_STF_YSL_2],
  },
  {
    id: "cl-marina" as ClientId,
    name: "Marina Becerra",
    phone: "5578901234",
    email: "marina.becerra@example.mx",
    birthday: "1983-03-14",
    city: "Ciudad de México",
    age: 43,
    preferredLang: "es-MX",
    since: "2019-09-08",
    tier: "Icon",
    brands: ["Lancôme"],
    storeId: ST_STF,
    skin: { type: "Madura", concerns: ["Firmeza", "Luminosidad"], tone: "Medio oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 4360, toNext: 640 },
    stats: { ltv: 91_200, visits: 8, avgTicket: 11_400, lastPurchase: "2026-04-18" },
    affinities: ["Absolue", "Génifique"],
    interests: ["Skincare", "Maquillaje"],
    routine: "Avanzada",
    createdByBaId: BA_STF_LCM_2,
    assignedBaIds: [BA_STF_LCM_2],
  },
  {
    id: "cl-nadia" as ClientId,
    name: "Nadia Hinojosa",
    phone: "5589012345",
    email: "nadia.hinojosa@example.mx",
    birthday: "1996-11-19",
    city: "Ciudad de México",
    age: 29,
    preferredLang: "es-MX",
    since: "2024-04-04",
    tier: "Icon",
    brands: ["YSL"],
    storeId: ST_STF,
    skin: { type: "Grasa", concerns: ["Acné adulto", "Poros"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 2890, toNext: 2110 },
    stats: { ltv: 28_700, visits: 3, avgTicket: 9_567, lastPurchase: "2025-12-10" },
    affinities: ["All Hours", "Touche Éclat"],
    interests: ["Maquillaje"],
    routine: "Intermedia",
    createdByBaId: BA_STF_YSL_1,
    assignedBaIds: [BA_STF_YSL_1],
  },
  {
    id: "cl-pamela" as ClientId,
    name: "Pamela Vázquez",
    phone: "5590123456",
    email: "pamela.vazquez@example.mx",
    birthday: "1999-05-08",
    city: "Ciudad de México",
    age: 26,
    preferredLang: "es-MX",
    since: "2025-11-21",
    tier: "Signature",
    brands: ["Lancôme"],
    storeId: ST_STF,
    skin: { type: "Seca", concerns: ["Hidratación"], tone: "Claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 560, toNext: 1440 },
    stats: { ltv: 5_640, visits: 1, avgTicket: 5_640, lastPurchase: "2026-02-08" },
    affinities: [],
    interests: ["Skincare"],
    routine: "Básica",
    createdByBaId: BA_STF_LCM_1,
    assignedBaIds: [BA_STF_LCM_1],
  },
  {
    id: "cl-rocio" as ClientId,
    name: "Rocío Castañeda",
    phone: "5501234567",
    email: "rocio.castaneda@example.mx",
    birthday: "1989-07-02",
    city: "Ciudad de México",
    age: 36,
    preferredLang: "es-MX",
    since: "2023-10-30",
    tier: "Signature",
    brands: ["Lancôme", "YSL"],
    storeId: ST_STF,
    skin: { type: "Normal", concerns: ["Luminosidad"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 1740, toNext: 260 },
    stats: { ltv: 18_900, visits: 2, avgTicket: 9_450, lastPurchase: "2026-01-25" },
    affinities: ["Libre"],
    interests: ["Fragancia"],
    routine: "Intermedia",
    createdByBaId: BA_STF_YSL_2,
    assignedBaIds: [BA_STF_YSL_2, BA_STF_YSL_1],
  },

  // ═════════════════════════════════════════════════════════════════════════
  // CLIENTES NUEVOS — segundo batch (post commit ownership por BA).
  //
  // Objetivo: que cada BA tenga 4-6 clientes propios para llenar demos.
  // Birthdays calibrados entre 3 y 60 días desde mayo 2026 — así cada BA
  // ve al menos un cumple próximo en su sección de Eventos.
  //
  // Distribución por tienda:
  //   2 LCM-only · 2 YSL-only · 2 multi-brand
  // ═════════════════════════════════════════════════════════════════════════

  // ── Polanco · 6 nuevos ────────────────────────────────────────────────────
  {
    id: "cl-mariana-pol" as ClientId,
    name: "Mariana Hernández",
    phone: "5512000001",
    email: "mariana.hernandez@example.mx",
    birthday: "1995-05-28",
    city: "Ciudad de México",
    age: 30,
    preferredLang: "es-MX",
    since: "2025-09-12",
    tier: "Signature",
    brands: ["Lancôme"],
    storeId: ST_POL,
    skin: { type: "Mixta", concerns: ["Hidratación", "Luminosidad"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 920, toNext: 1080 },
    stats: { ltv: 7_840, visits: 2, avgTicket: 3_920, lastPurchase: "2026-04-08" },
    affinities: ["Hydra Zen"],
    interests: ["Skincare"],
    routine: "Básica",
    createdByBaId: BA_POL_LCM_1,
    assignedBaIds: [BA_POL_LCM_1],
  },
  {
    id: "cl-andrea-pol" as ClientId,
    name: "Andrea Solórzano",
    phone: "5512000002",
    email: "andrea.solorzano@example.mx",
    birthday: "1984-06-15",
    city: "Ciudad de México",
    age: 41,
    preferredLang: "es-MX",
    since: "2022-11-03",
    tier: "Icon",
    brands: ["Lancôme"],
    storeId: ST_POL,
    skin: { type: "Madura", concerns: ["Firmeza", "Arrugas profundas"], tone: "Medio cálido", subtone: "cálido" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 4180, toNext: 820 },
    stats: { ltv: 64_300, visits: 6, avgTicket: 10_717, lastPurchase: "2026-04-02" },
    affinities: ["Absolue"],
    interests: ["Skincare", "Maquillaje"],
    routine: "Avanzada",
    createdByBaId: BA_POL_LCM_2,
    assignedBaIds: [BA_POL_LCM_2],
  },
  {
    id: "cl-paloma-pol" as ClientId,
    name: "Paloma Arellano",
    phone: "5512000003",
    email: "paloma.arellano@example.mx",
    birthday: "1989-06-30",
    city: "Ciudad de México",
    age: 36,
    preferredLang: "es-MX",
    since: "2020-08-17",
    tier: "Atelier",
    brands: ["YSL"],
    storeId: ST_POL,
    skin: { type: "Normal", concerns: ["Luminosidad"], tone: "Claro", subtone: "neutro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 8920, toNext: 0 },
    stats: { ltv: 196_400, visits: 12, avgTicket: 16_367, lastPurchase: "2026-04-19" },
    affinities: ["Libre", "Tatouage Couture"],
    interests: ["Maquillaje", "Fragancia"],
    routine: "Profesional",
    createdByBaId: BA_POL_YSL_2,
    assignedBaIds: [BA_POL_YSL_2],
  },
  {
    id: "cl-vanessa-pol" as ClientId,
    name: "Vanessa Domínguez",
    phone: "5512000004",
    email: "vanessa.dominguez@example.mx",
    birthday: "1997-07-11",
    city: "Ciudad de México",
    age: 28,
    preferredLang: "es-MX",
    since: "2024-02-09",
    tier: "Icon",
    brands: ["YSL"],
    storeId: ST_POL,
    skin: { type: "Mixta", concerns: ["Poros", "Luminosidad"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 3120, toNext: 1880 },
    stats: { ltv: 41_200, visits: 4, avgTicket: 10_300, lastPurchase: "2026-03-22" },
    affinities: ["Black Opium"],
    interests: ["Fragancia", "Maquillaje"],
    routine: "Intermedia",
    createdByBaId: BA_POL_YSL_1,
    assignedBaIds: [BA_POL_YSL_1],
  },
  {
    id: "cl-monica-pol" as ClientId,
    name: "Mónica Tovar",
    phone: "5512000005",
    email: "monica.tovar@example.mx",
    birthday: "1986-07-25",
    city: "Ciudad de México",
    age: 39,
    preferredLang: "es-MX",
    since: "2019-12-04",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_POL,
    skin: { type: "Madura", concerns: ["Líneas finas", "Firmeza"], tone: "Medio cálido", subtone: "cálido" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 9540, toNext: 0 },
    stats: { ltv: 212_800, visits: 15, avgTicket: 14_187, lastPurchase: "2026-04-30" },
    affinities: ["Rénergie", "Or Rouge"],
    interests: ["Skincare", "Maquillaje", "Fragancia"],
    routine: "Profesional",
    createdByBaId: BA_POL_LCM_2,
    assignedBaIds: [BA_POL_LCM_2, BA_POL_YSL_2],
  },
  {
    id: "cl-pilar-pol" as ClientId,
    name: "Pilar Estévez",
    phone: "5512000006",
    email: "pilar.estevez@example.mx",
    birthday: "1993-06-04",
    city: "Ciudad de México",
    age: 32,
    preferredLang: "es-MX",
    since: "2026-01-22",
    tier: "Signature",
    brands: ["Lancôme", "YSL"],
    storeId: ST_POL,
    skin: { type: "Seca", concerns: ["Hidratación"], tone: "Claro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 380, toNext: 1620 },
    stats: { ltv: 3_640, visits: 1, avgTicket: 3_640, lastPurchase: "2026-04-15" },
    affinities: [],
    interests: ["Skincare", "Fragancia"],
    routine: "Básica",
    createdByBaId: BA_POL_LCM_1,
    assignedBaIds: [BA_POL_LCM_1, BA_POL_YSL_1],
  },

  // ── Perisur · 6 nuevos ────────────────────────────────────────────────────
  {
    id: "cl-natalia-per" as ClientId,
    name: "Natalia Cárdenas",
    phone: "5523000001",
    email: "natalia.cardenas@example.mx",
    birthday: "1981-06-08",
    city: "Ciudad de México",
    age: 44,
    preferredLang: "es-MX",
    since: "2018-05-14",
    tier: "Atelier",
    brands: ["Lancôme"],
    storeId: ST_PER,
    skin: { type: "Madura", concerns: ["Arrugas profundas", "Manchas"], tone: "Medio oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 9120, toNext: 0 },
    stats: { ltv: 234_500, visits: 17, avgTicket: 13_794, lastPurchase: "2026-05-02" },
    affinities: ["Absolue", "Rénergie"],
    interests: ["Skincare"],
    routine: "Profesional",
    createdByBaId: BA_PER_LCM_2,
    assignedBaIds: [BA_PER_LCM_2],
  },
  {
    id: "cl-claudia-per" as ClientId,
    name: "Claudia Sotelo",
    phone: "5523000002",
    email: "claudia.sotelo@example.mx",
    birthday: "1990-06-20",
    city: "Ciudad de México",
    age: 35,
    preferredLang: "es-MX",
    since: "2023-04-08",
    tier: "Icon",
    brands: ["Lancôme"],
    storeId: ST_PER,
    skin: { type: "Mixta", concerns: ["Luminosidad", "Poros"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 3260, toNext: 1740 },
    stats: { ltv: 47_800, visits: 5, avgTicket: 9_560, lastPurchase: "2026-04-11" },
    affinities: ["Génifique"],
    interests: ["Skincare"],
    routine: "Avanzada",
    createdByBaId: BA_PER_LCM_1,
    assignedBaIds: [BA_PER_LCM_1],
  },
  {
    id: "cl-jessica-per" as ClientId,
    name: "Jessica Romero",
    phone: "5523000003",
    email: "jessica.romero@example.mx",
    birthday: "1998-07-03",
    city: "Ciudad de México",
    age: 27,
    preferredLang: "es-MX",
    since: "2025-08-21",
    tier: "Signature",
    brands: ["YSL"],
    storeId: ST_PER,
    skin: { type: "Grasa", concerns: ["Acné adulto", "Poros"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 560, toNext: 1440 },
    stats: { ltv: 4_290, visits: 1, avgTicket: 4_290, lastPurchase: "2026-04-26" },
    affinities: [],
    interests: ["Maquillaje"],
    routine: "Básica",
    createdByBaId: BA_PER_YSL_2,
    assignedBaIds: [BA_PER_YSL_2],
  },
  {
    id: "cl-yolanda-per" as ClientId,
    name: "Yolanda Páez",
    phone: "5523000004",
    email: "yolanda.paez@example.mx",
    birthday: "1979-07-19",
    city: "Ciudad de México",
    age: 46,
    preferredLang: "es-MX",
    since: "2017-03-29",
    tier: "Atelier",
    brands: ["YSL"],
    storeId: ST_PER,
    skin: { type: "Madura", concerns: ["Firmeza", "Líneas finas"], tone: "Medio cálido", subtone: "cálido" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 9870, toNext: 0 },
    stats: { ltv: 252_300, visits: 18, avgTicket: 14_017, lastPurchase: "2026-04-30" },
    affinities: ["Or Rouge", "Libre"],
    interests: ["Skincare", "Fragancia"],
    routine: "Profesional",
    createdByBaId: BA_PER_YSL_1,
    assignedBaIds: [BA_PER_YSL_1],
  },
  {
    id: "cl-sandra-per" as ClientId,
    name: "Sandra Coronel",
    phone: "5523000005",
    email: "sandra.coronel@example.mx",
    birthday: "1992-06-12",
    city: "Ciudad de México",
    age: 33,
    preferredLang: "es-MX",
    since: "2024-09-30",
    tier: "Icon",
    brands: ["Lancôme", "YSL"],
    storeId: ST_PER,
    skin: { type: "Mixta", concerns: ["Luminosidad", "Hidratación"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 2950, toNext: 2050 },
    stats: { ltv: 38_400, visits: 4, avgTicket: 9_600, lastPurchase: "2026-04-22" },
    affinities: ["Génifique", "Black Opium"],
    interests: ["Skincare", "Fragancia"],
    routine: "Intermedia",
    createdByBaId: BA_PER_LCM_2,
    assignedBaIds: [BA_PER_LCM_2, BA_PER_YSL_2],
  },
  {
    id: "cl-veronica-per" as ClientId,
    name: "Verónica Llanos",
    phone: "5523000006",
    email: "veronica.llanos@example.mx",
    birthday: "1984-07-28",
    city: "Ciudad de México",
    age: 41,
    preferredLang: "es-MX",
    since: "2019-10-11",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_PER,
    skin: { type: "Madura", concerns: ["Manchas", "Luminosidad"], tone: "Medio cálido" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 8780, toNext: 0 },
    stats: { ltv: 198_700, visits: 13, avgTicket: 15_285, lastPurchase: "2026-04-18" },
    affinities: ["Absolue", "Libre"],
    interests: ["Skincare", "Maquillaje", "Fragancia"],
    routine: "Profesional",
    createdByBaId: BA_PER_LCM_1,
    assignedBaIds: [BA_PER_LCM_1, BA_PER_YSL_1],
  },

  // ── Santa Fe · 6 nuevos ───────────────────────────────────────────────────
  {
    id: "cl-laura-stf" as ClientId,
    name: "Laura Bustamante",
    phone: "5534000001",
    email: "laura.bustamante@example.mx",
    birthday: "1980-06-25",
    city: "Ciudad de México",
    age: 45,
    preferredLang: "es-MX",
    since: "2016-07-22",
    tier: "Atelier",
    brands: ["Lancôme"],
    storeId: ST_STF,
    skin: { type: "Madura", concerns: ["Arrugas profundas", "Firmeza"], tone: "Oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 9450, toNext: 0 },
    stats: { ltv: 268_400, visits: 19, avgTicket: 14_126, lastPurchase: "2026-04-27" },
    affinities: ["Rénergie", "Absolue Eye"],
    interests: ["Skincare"],
    routine: "Profesional",
    createdByBaId: BA_STF_LCM_2,
    assignedBaIds: [BA_STF_LCM_2],
  },
  {
    id: "cl-irma-stf" as ClientId,
    name: "Irma Gallegos",
    phone: "5534000002",
    email: "irma.gallegos@example.mx",
    birthday: "2001-07-14",
    city: "Ciudad de México",
    age: 24,
    preferredLang: "es-MX",
    since: "2026-03-04",
    tier: "Signature",
    brands: ["Lancôme"],
    storeId: ST_STF,
    skin: { type: "Grasa", concerns: ["Acné adulto", "Textura"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 240, toNext: 1760 },
    stats: { ltv: 2_280, visits: 1, avgTicket: 2_280, lastPurchase: "2026-04-29" },
    affinities: [],
    interests: ["Skincare", "Maquillaje"],
    routine: "Básica",
    createdByBaId: BA_STF_LCM_1,
    assignedBaIds: [BA_STF_LCM_1],
  },
  {
    id: "cl-luisa-stf" as ClientId,
    name: "Luisa Camarena",
    phone: "5534000003",
    email: "luisa.camarena@example.mx",
    birthday: "1988-07-08",
    city: "Ciudad de México",
    age: 37,
    preferredLang: "es-MX",
    since: "2021-06-15",
    tier: "Icon",
    brands: ["YSL"],
    storeId: ST_STF,
    skin: { type: "Normal", concerns: ["Luminosidad"], tone: "Medio claro", subtone: "neutro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 3680, toNext: 1320 },
    stats: { ltv: 58_900, visits: 6, avgTicket: 9_817, lastPurchase: "2026-04-09" },
    affinities: ["Tatouage Couture", "Touche Éclat"],
    interests: ["Maquillaje", "Fragancia"],
    routine: "Intermedia",
    createdByBaId: BA_STF_YSL_1,
    assignedBaIds: [BA_STF_YSL_1],
  },
  {
    id: "cl-fernanda-stf" as ClientId,
    name: "Fernanda Quesada",
    phone: "5534000004",
    email: "fernanda.quesada@example.mx",
    birthday: "2000-05-30",
    city: "Ciudad de México",
    age: 25,
    preferredLang: "es-MX",
    since: "2025-12-17",
    tier: "Signature",
    brands: ["YSL"],
    storeId: ST_STF,
    skin: { type: "Sensible", concerns: ["Rojeces", "Sensibilidad"], tone: "Claro" },
    allergies: ["Alcohol"],
    loyalty: { name: "Luxe Circle", tier: "Signature", points: 480, toNext: 1520 },
    stats: { ltv: 4_120, visits: 1, avgTicket: 4_120, lastPurchase: "2026-04-03" },
    affinities: ["Loveshine"],
    interests: ["Maquillaje"],
    routine: "Básica",
    createdByBaId: BA_STF_YSL_2,
    assignedBaIds: [BA_STF_YSL_2],
  },
  {
    id: "cl-bertha-stf" as ClientId,
    name: "Bertha Olivares",
    phone: "5534000005",
    email: "bertha.olivares@example.mx",
    birthday: "1976-07-22",
    city: "Ciudad de México",
    age: 49,
    preferredLang: "es-MX",
    since: "2015-04-09",
    tier: "Atelier",
    brands: ["Lancôme", "YSL"],
    storeId: ST_STF,
    skin: { type: "Madura", concerns: ["Firmeza", "Manchas"], tone: "Medio oscuro" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Atelier", points: 9980, toNext: 0 },
    stats: { ltv: 304_200, visits: 22, avgTicket: 13_827, lastPurchase: "2026-05-01" },
    affinities: ["Absolue", "Or Rouge"],
    interests: ["Skincare", "Maquillaje", "Fragancia"],
    routine: "Profesional",
    createdByBaId: BA_STF_LCM_2,
    assignedBaIds: [BA_STF_LCM_2, BA_STF_YSL_2],
  },
  {
    id: "cl-tatiana-stf" as ClientId,
    name: "Tatiana Ferreyra",
    phone: "5534000006",
    email: "tatiana.ferreyra@example.mx",
    birthday: "1991-06-10",
    city: "Ciudad de México",
    age: 34,
    preferredLang: "es-MX",
    since: "2023-08-26",
    tier: "Icon",
    brands: ["Lancôme", "YSL"],
    storeId: ST_STF,
    skin: { type: "Mixta", concerns: ["Hidratación", "Luminosidad"], tone: "Medio" },
    allergies: [],
    loyalty: { name: "Luxe Circle", tier: "Icon", points: 4290, toNext: 710 },
    stats: { ltv: 71_400, visits: 7, avgTicket: 10_200, lastPurchase: "2026-04-14" },
    affinities: ["Hydra Zen", "Lash Clash"],
    interests: ["Skincare", "Maquillaje"],
    routine: "Avanzada",
    createdByBaId: BA_STF_LCM_1,
    assignedBaIds: [BA_STF_LCM_1, BA_STF_YSL_1],
  },
];

export const SEED_PURCHASES: Purchase[] = [
  // ── Polanco ───────────────────────────────────────────────────────────────
  // Constanza (multi-brand) gets a LCM purchase by BA Lancôme...
  {
    id: "pu-1" as Purchase["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    storeId: ST_POL,
    at: "2026-04-21T18:32:00.000Z",
    items: [
      { sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 9_800 },
      { sku: "LC-GEN-50" as Sku, qty: 1, unitPrice: 6_400 },
    ],
    total: 16_200,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260421-0892",
  },
  // ...and a separate YSL purchase by BA YSL (Option A in action).
  {
    id: "pu-2" as Purchase["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_YSL_1,
    storeId: ST_POL,
    at: "2026-03-12T15:10:00.000Z",
    items: [{ sku: "YS-LIB-90" as Sku, qty: 1, unitPrice: 8_900 }],
    total: 8_900,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260312-0421",
  },
  {
    id: "pu-3" as Purchase["id"],
    clientId: "cl-ofelia" as ClientId,
    baId: BA_POL_LCM_2,
    storeId: ST_POL,
    at: "2026-04-02T16:11:00.000Z",
    items: [{ sku: "LC-HZN-50" as Sku, qty: 1, unitPrice: 12_100 }],
    total: 12_100,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260402-0145",
  },
  {
    id: "pu-4" as Purchase["id"],
    clientId: "cl-adriana" as ClientId,
    baId: BA_POL_YSL_2,
    storeId: ST_POL,
    at: "2026-03-18T15:45:00.000Z",
    items: [{ sku: "YS-LIB-90" as Sku, qty: 1, unitPrice: 8_900 }],
    total: 8_900,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260318-0312",
  },

  // ── Perisur ───────────────────────────────────────────────────────────────
  {
    id: "pu-5" as Purchase["id"],
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    storeId: ST_PER,
    at: "2026-04-25T17:00:00.000Z",
    items: [{ sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 9_800 }],
    total: 9_800,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260425-0118",
  },
  {
    id: "pu-6" as Purchase["id"],
    clientId: "cl-elena" as ClientId,
    baId: BA_PER_LCM_2,
    storeId: ST_PER,
    at: "2026-03-10T11:20:00.000Z",
    items: [{ sku: "LC-GEN-50" as Sku, qty: 1, unitPrice: 6_400 }],
    total: 6_400,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260310-0207",
  },
  {
    id: "pu-7" as Purchase["id"],
    clientId: "cl-ines" as ClientId,
    baId: BA_PER_YSL_2,
    storeId: ST_PER,
    at: "2026-04-12T19:05:00.000Z",
    items: [{ sku: "YS-RPC-01" as Sku, qty: 4, unitPrice: 950 }],
    total: 3_800,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260412-0498",
  },
  {
    id: "pu-8" as Purchase["id"],
    clientId: "cl-julieta" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    at: "2026-02-22T13:25:00.000Z",
    items: [{ sku: "YS-OR-100" as Sku, qty: 1, unitPrice: 6_490 }],
    total: 6_490,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260222-0061",
  },

  // ── Santa Fe ──────────────────────────────────────────────────────────────
  {
    id: "pu-9" as Purchase["id"],
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_LCM_1,
    storeId: ST_STF,
    at: "2026-04-28T16:30:00.000Z",
    items: [
      { sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 9_800 },
      { sku: "LC-HZN-50" as Sku, qty: 1, unitPrice: 12_100 },
    ],
    total: 21_900,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "PH-260428-0931",
  },
  {
    id: "pu-10" as Purchase["id"],
    clientId: "cl-marina" as ClientId,
    baId: BA_STF_LCM_2,
    storeId: ST_STF,
    at: "2026-04-18T14:15:00.000Z",
    items: [{ sku: "LC-GEN-50" as Sku, qty: 1, unitPrice: 6_400 }],
    total: 6_400,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "PH-260418-0577",
  },
  {
    id: "pu-11" as Purchase["id"],
    clientId: "cl-nadia" as ClientId,
    baId: BA_STF_YSL_1,
    storeId: ST_STF,
    at: "2025-12-10T18:00:00.000Z",
    items: [{ sku: "YS-OR-100" as Sku, qty: 1, unitPrice: 6_490 }],
    total: 6_490,
    payment: "card",
    brand: "YSL",
    ticketRef: "PH-251210-0188",
  },
  {
    id: "pu-12" as Purchase["id"],
    clientId: "cl-rocio" as ClientId,
    baId: BA_STF_YSL_2,
    storeId: ST_STF,
    at: "2026-01-25T18:00:00.000Z",
    items: [{ sku: "YS-LIB-90" as Sku, qty: 1, unitPrice: 8_900 }],
    total: 8_900,
    payment: "card",
    brand: "YSL",
    ticketRef: "PH-260125-0244",
  },

  // ── Historic purchases for retention KPIs ──────────────────────────────────
  // Older purchases (Aug–Sep 2025) anchor the default 6-month cohort window
  // for getRepurchaseRate. Some clientas repurchase later (via existing
  // 2026 purchases), some don't — giving the cohort signal in every bucket.
  {
    id: "pu-13" as Purchase["id"],
    clientId: "cl-elena" as ClientId, // Perisur LCM (since 2020-11-04)
    baId: BA_PER_LCM_2,
    storeId: ST_PER,
    at: "2025-09-15T16:00:00.000Z",
    items: [{ sku: "LC-GEN-50" as Sku, qty: 1, unitPrice: 6_400 }],
    total: 6_400,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-250915-0731",
  },
  {
    id: "pu-14" as Purchase["id"],
    clientId: "cl-elena" as ClientId, // Repurchase by cl-elena
    baId: BA_PER_LCM_2,
    storeId: ST_PER,
    at: "2026-02-10T14:30:00.000Z",
    items: [{ sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 9_800 }],
    total: 9_800,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260210-0294",
  },
  {
    id: "pu-15" as Purchase["id"],
    clientId: "cl-gabriela" as ClientId, // Perisur YSL (since 2023-03-20) — cohort SIN repurchase
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    at: "2025-09-10T13:00:00.000Z",
    items: [{ sku: "YS-LIB-90" as Sku, qty: 1, unitPrice: 8_900 }],
    total: 8_900,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-250910-0512",
  },
  {
    id: "pu-16" as Purchase["id"],
    clientId: "cl-constanza" as ClientId, // Polanco LCM cohort — repurchase later via pu-1
    baId: BA_POL_LCM_1,
    storeId: ST_POL,
    at: "2025-08-15T16:00:00.000Z",
    items: [{ sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 9_800 }],
    total: 9_800,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-250815-0177",
  },

  // ── YSL · tickets con catálogo expandido ──────────────────────────────────
  // Estos tickets usan los SKUs nuevos del catálogo YSL (Black Opium,
  // Tatouage Couture, Lash Clash, Y EDP, Pure Shots) — antes el seed solo
  // movía Libre / Or Rouge / Rouge Pur Couture y dejaba el resto sin
  // tracking. Útil para demostrar reportes BA YSL con mix realista.
  {
    id: "pu-17" as Purchase["id"],
    clientId: "cl-rocio" as ClientId, // multi-brand Santa Fe
    baId: BA_STF_YSL_1,
    storeId: ST_STF,
    at: "2026-04-15T17:20:00.000Z",
    items: [
      { sku: "YS-BO-50" as Sku, qty: 1, unitPrice: 2_650 },
      { sku: "YS-TC-01" as Sku, qty: 1, unitPrice: 990 },
    ],
    total: 3_640,
    payment: "card",
    brand: "YSL",
    ticketRef: "PH-260415-0738",
  },
  {
    id: "pu-18" as Purchase["id"],
    clientId: "cl-gabriela" as ClientId, // YSL pura Perisur
    baId: BA_PER_YSL_2,
    storeId: ST_PER,
    at: "2026-04-22T15:45:00.000Z",
    items: [
      { sku: "YS-PSE-15" as Sku, qty: 1, unitPrice: 2_280 },
      { sku: "YS-LC-01" as Sku, qty: 1, unitPrice: 940 },
    ],
    total: 3_220,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260422-0613",
  },
  {
    id: "pu-19" as Purchase["id"],
    clientId: "cl-karla" as ClientId, // multi-brand Santa Fe — compra de regalo masculino
    baId: BA_STF_YSL_2,
    storeId: ST_STF,
    at: "2026-04-29T19:10:00.000Z",
    items: [{ sku: "YS-Y-60" as Sku, qty: 1, unitPrice: 2_950 }],
    total: 2_950,
    payment: "card",
    brand: "YSL",
    ticketRef: "PH-260429-0904",
  },

  // ── Compras nuevos clientes ────────────────────────────────────────────
  {
    id: "pu-20" as Purchase["id"],
    clientId: "cl-monica-pol" as ClientId,
    baId: BA_POL_LCM_2,
    storeId: ST_POL,
    at: "2026-04-30T16:20:00.000Z",
    items: [
      { sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 6_700 },
      { sku: "LC-GEN-50" as Sku, qty: 1, unitPrice: 2_250 },
    ],
    total: 8_950,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260430-0721",
  },
  {
    id: "pu-21" as Purchase["id"],
    clientId: "cl-paloma-pol" as ClientId,
    baId: BA_POL_YSL_2,
    storeId: ST_POL,
    at: "2026-04-19T15:00:00.000Z",
    items: [
      { sku: "YS-LIB-90" as Sku, qty: 1, unitPrice: 4_120 },
      { sku: "YS-TC-01" as Sku, qty: 1, unitPrice: 990 },
    ],
    total: 5_110,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260419-0512",
  },
  {
    id: "pu-22" as Purchase["id"],
    clientId: "cl-vanessa-pol" as ClientId,
    baId: BA_POL_YSL_1,
    storeId: ST_POL,
    at: "2026-03-22T17:30:00.000Z",
    items: [{ sku: "YS-BO-50" as Sku, qty: 1, unitPrice: 2_650 }],
    total: 2_650,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260322-0388",
  },
  {
    id: "pu-23" as Purchase["id"],
    clientId: "cl-andrea-pol" as ClientId,
    baId: BA_POL_LCM_2,
    storeId: ST_POL,
    at: "2026-04-02T13:45:00.000Z",
    items: [{ sku: "LC-REN-50" as Sku, qty: 1, unitPrice: 3_250 }],
    total: 3_250,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260402-0244",
  },
  {
    id: "pu-24" as Purchase["id"],
    clientId: "cl-natalia-per" as ClientId,
    baId: BA_PER_LCM_2,
    storeId: ST_PER,
    at: "2026-05-02T14:30:00.000Z",
    items: [
      { sku: "LC-REN-50" as Sku, qty: 1, unitPrice: 3_250 },
      { sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 6_700 },
    ],
    total: 9_950,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260502-0817",
  },
  {
    id: "pu-25" as Purchase["id"],
    clientId: "cl-yolanda-per" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    at: "2026-04-30T16:00:00.000Z",
    items: [
      { sku: "YS-OR-100" as Sku, qty: 1, unitPrice: 6_490 },
      { sku: "YS-PSE-15" as Sku, qty: 1, unitPrice: 2_280 },
    ],
    total: 8_770,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260430-0633",
  },
  {
    id: "pu-26" as Purchase["id"],
    clientId: "cl-sandra-per" as ClientId,
    baId: BA_PER_LCM_2,
    storeId: ST_PER,
    at: "2026-04-22T17:15:00.000Z",
    items: [{ sku: "LC-HZN-50" as Sku, qty: 1, unitPrice: 1_550 }],
    total: 1_550,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "LV-260422-0497",
  },
  {
    id: "pu-27" as Purchase["id"],
    clientId: "cl-veronica-per" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    at: "2026-04-18T14:00:00.000Z",
    items: [{ sku: "YS-LIB-90" as Sku, qty: 1, unitPrice: 4_120 }],
    total: 4_120,
    payment: "card",
    brand: "YSL",
    ticketRef: "LV-260418-0419",
  },
  {
    id: "pu-28" as Purchase["id"],
    clientId: "cl-laura-stf" as ClientId,
    baId: BA_STF_LCM_2,
    storeId: ST_STF,
    at: "2026-04-27T15:30:00.000Z",
    items: [
      { sku: "LC-ABS-50" as Sku, qty: 1, unitPrice: 6_700 },
      { sku: "LC-AEC-20" as Sku, qty: 1, unitPrice: 2_860 },
    ],
    total: 9_560,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "PH-260427-0902",
  },
  {
    id: "pu-29" as Purchase["id"],
    clientId: "cl-bertha-stf" as ClientId,
    baId: BA_STF_YSL_2,
    storeId: ST_STF,
    at: "2026-05-01T18:00:00.000Z",
    items: [
      { sku: "YS-OR-100" as Sku, qty: 1, unitPrice: 6_490 },
      { sku: "YS-BO-50" as Sku, qty: 1, unitPrice: 2_650 },
    ],
    total: 9_140,
    payment: "card",
    brand: "YSL",
    ticketRef: "PH-260501-0851",
  },
  {
    id: "pu-30" as Purchase["id"],
    clientId: "cl-luisa-stf" as ClientId,
    baId: BA_STF_YSL_1,
    storeId: ST_STF,
    at: "2026-04-09T16:45:00.000Z",
    items: [
      { sku: "YS-TC-01" as Sku, qty: 1, unitPrice: 990 },
      { sku: "YS-TCL-02" as Sku, qty: 1, unitPrice: 1_180 },
    ],
    total: 2_170,
    payment: "card",
    brand: "YSL",
    ticketRef: "PH-260409-0712",
  },
  {
    id: "pu-31" as Purchase["id"],
    clientId: "cl-tatiana-stf" as ClientId,
    baId: BA_STF_LCM_1,
    storeId: ST_STF,
    at: "2026-04-14T13:00:00.000Z",
    items: [
      { sku: "LC-HZN-50" as Sku, qty: 1, unitPrice: 1_550 },
      { sku: "YS-LC-01" as Sku, qty: 1, unitPrice: 940 },
    ],
    total: 2_490,
    payment: "card",
    brand: "Lancôme",
    ticketRef: "PH-260414-0588",
  },
];

/**
 * Interactions cover the operational mix every dashboard query needs:
 * sales, consultations, samples, whatsapp, followups, returns and courtesy
 * visits — across all three stores and both brands, spread across the last
 * ~45 days so date-range queries (last 7d / last 30d / comparable period)
 * have signal in every bucket.
 */
export const SEED_INTERACTIONS: Interaction[] = [
  // ── Polanco · Lancôme ───────────────────────────────────────────────────────
  {
    id: "int-1" as Interaction["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    brand: "Lancôme",
    storeId: ST_POL,
    kind: "purchase",
    at: "2026-04-21T18:32:00.000Z",
    amount: 16_200,
  },
  {
    id: "int-2" as Interaction["id"],
    clientId: "cl-ofelia" as ClientId,
    baId: BA_POL_LCM_2,
    brand: "Lancôme",
    storeId: ST_POL,
    kind: "sample",
    at: "2026-04-08T14:20:00.000Z",
    notes: "Muestra Hydrating Boost 7d.",
  },
  {
    id: "int-3" as Interaction["id"],
    clientId: "cl-lorena" as ClientId,
    baId: BA_POL_LCM_1,
    brand: "Lancôme",
    storeId: ST_POL,
    kind: "consultation",
    at: "2026-05-02T11:15:00.000Z",
    durationMin: 30,
    notes: "Diagnóstico inicial piel grasa.",
  },
  {
    id: "int-4" as Interaction["id"],
    clientId: "cl-beatriz" as ClientId,
    baId: BA_POL_LCM_2,
    brand: "Lancôme",
    storeId: ST_POL,
    kind: "whatsapp",
    at: "2026-05-10T16:00:00.000Z",
    notes: "Confirma cita facial.",
  },
  // ── Polanco · YSL ───────────────────────────────────────────────────────────
  {
    id: "int-5" as Interaction["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_YSL_1,
    brand: "YSL",
    storeId: ST_POL,
    kind: "consultation",
    at: "2026-03-15T15:00:00.000Z",
    durationMin: 45,
    notes: "Renovó descubrimiento Or Rouge; interesada en travel size.",
  },
  {
    id: "int-6" as Interaction["id"],
    clientId: "cl-adriana" as ClientId,
    baId: BA_POL_YSL_2,
    brand: "YSL",
    storeId: ST_POL,
    kind: "purchase",
    at: "2026-03-18T15:30:00.000Z",
    amount: 8_900,
  },
  {
    id: "int-7" as Interaction["id"],
    clientId: "cl-beatriz" as ClientId,
    baId: BA_POL_YSL_1,
    brand: "YSL",
    storeId: ST_POL,
    kind: "sample",
    at: "2026-05-04T17:00:00.000Z",
    notes: "Vial Libre Le Parfum.",
  },

  // ── Perisur · Lancôme ───────────────────────────────────────────────────────
  {
    id: "int-8" as Interaction["id"],
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    brand: "Lancôme",
    storeId: ST_PER,
    kind: "purchase",
    at: "2026-04-25T16:30:00.000Z",
    amount: 14_500,
  },
  {
    id: "int-9" as Interaction["id"],
    clientId: "cl-elena" as ClientId,
    baId: BA_PER_LCM_2,
    brand: "Lancôme",
    storeId: ST_PER,
    kind: "followup",
    at: "2026-05-05T10:00:00.000Z",
    notes: "Seguimiento post-cumpleaños.",
  },
  {
    id: "int-10" as Interaction["id"],
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    brand: "Lancôme",
    storeId: ST_PER,
    kind: "courtesy",
    at: "2026-05-12T14:00:00.000Z",
    notes: "Pasó a saludar.",
  },
  // ── Perisur · YSL ───────────────────────────────────────────────────────────
  {
    id: "int-11" as Interaction["id"],
    clientId: "cl-gabriela" as ClientId,
    baId: BA_PER_YSL_1,
    brand: "YSL",
    storeId: ST_PER,
    kind: "consultation",
    at: "2026-03-09T15:10:00.000Z",
    durationMin: 40,
    notes: "Recomendó Libre + All Hours.",
  },
  {
    id: "int-12" as Interaction["id"],
    clientId: "cl-julieta" as ClientId,
    baId: BA_PER_YSL_2,
    brand: "YSL",
    storeId: ST_PER,
    kind: "sample",
    at: "2026-05-08T12:30:00.000Z",
    notes: "Hydrating Boost 7d adaptado a piel sensible.",
  },
  {
    id: "int-13" as Interaction["id"],
    clientId: "cl-ines" as ClientId,
    baId: BA_PER_YSL_1,
    brand: "YSL",
    storeId: ST_PER,
    kind: "purchase",
    at: "2026-04-12T17:45:00.000Z",
    amount: 3_800,
  },

  // ── Santa Fe · Lancôme ──────────────────────────────────────────────────────
  {
    id: "int-14" as Interaction["id"],
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_LCM_1,
    brand: "Lancôme",
    storeId: ST_STF,
    kind: "purchase",
    at: "2026-04-28T16:00:00.000Z",
    amount: 22_800,
  },
  {
    id: "int-15" as Interaction["id"],
    clientId: "cl-marina" as ClientId,
    baId: BA_STF_LCM_2,
    brand: "Lancôme",
    storeId: ST_STF,
    kind: "consultation",
    at: "2026-04-18T11:00:00.000Z",
    durationMin: 50,
    notes: "Renovación rutina antiedad.",
  },
  {
    id: "int-16" as Interaction["id"],
    clientId: "cl-pamela" as ClientId,
    baId: BA_STF_LCM_1,
    brand: "Lancôme",
    storeId: ST_STF,
    kind: "sample",
    at: "2026-05-07T13:00:00.000Z",
    notes: "Crema Absolue 5ml.",
  },
  // ── Santa Fe · YSL ──────────────────────────────────────────────────────────
  {
    id: "int-17" as Interaction["id"],
    clientId: "cl-nadia" as ClientId,
    baId: BA_STF_YSL_1,
    brand: "YSL",
    storeId: ST_STF,
    kind: "consultation",
    at: "2025-12-09T11:30:00.000Z",
    durationMin: 35,
    notes: "Recomendó rutina anti-acné.",
  },
  {
    id: "int-18" as Interaction["id"],
    clientId: "cl-rocio" as ClientId,
    baId: BA_STF_YSL_2,
    brand: "YSL",
    storeId: ST_STF,
    kind: "purchase",
    at: "2026-01-25T18:00:00.000Z",
    amount: 8_900,
  },
  {
    id: "int-19" as Interaction["id"],
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_YSL_2,
    brand: "YSL",
    storeId: ST_STF,
    kind: "whatsapp",
    at: "2026-05-13T10:00:00.000Z",
    notes: "Le aparta Libre Le Parfum.",
  },
  // ── Test fixtures for getFollowUpToRevisitRate ──────────────────────────────
  // int-20: revisita PRESENCIAL de cl-marina por OTRA BA del mismo counter
  // (STF × Lancôme) tras ft-08. Demuestra "otro BA del mismo counter SÍ cuenta".
  {
    id: "int-20" as Interaction["id"],
    clientId: "cl-marina" as ClientId,
    baId: BA_STF_LCM_1, // Renata, distinta de la BA del ft-08 (Ximena)
    brand: "Lancôme",
    storeId: ST_STF,
    kind: "consultation",
    at: "2026-05-04T15:00:00.000Z",
    durationMin: 35,
    notes: "Renueva diagnóstico (revisita post-followup).",
  },
  // int-21: WhatsApp posterior a ft-07 — NO debe contar como revisita
  // porque la regla excluye comunicación remota.
  {
    id: "int-21" as Interaction["id"],
    clientId: "cl-gabriela" as ClientId,
    baId: BA_PER_YSL_1,
    brand: "YSL",
    storeId: ST_PER,
    kind: "whatsapp",
    at: "2026-04-25T11:00:00.000Z",
    notes: "Confirma recibo de muestra (no cuenta como revisita).",
  },
];

/**
 * Samples cover three states (delivered & pending, converted with purchase,
 * overdue with no follow-up) across all three stores and both brands so the
 * sample-conversion KPI has data in every bucket.
 */
export const SEED_SAMPLES: Sample[] = [
  // Polanco · Lancôme — pending follow-up
  {
    id: "sp-1" as Sample["id"],
    clientId: "cl-ofelia" as ClientId,
    baId: BA_POL_LCM_2,
    storeId: ST_POL,
    brand: "Lancôme",
    sku: "LC-HZN-7" as Sku,
    name: "Hydrating Boost · 7d",
    givenAt: "2026-04-08T14:20:00.000Z",
    followUpAt: "2026-04-22T00:00:00.000Z",
    converted: false,
  },
  // Polanco · Lancôme — converted (linked to pu-1)
  {
    id: "sp-2" as Sample["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    storeId: ST_POL,
    brand: "Lancôme",
    sku: "LC-GEN-7" as Sku,
    name: "Advanced Génifique · 7ml",
    givenAt: "2026-04-12T16:00:00.000Z",
    converted: true,
    purchaseId: "pu-1" as Purchase["id"],
  },
  // Polanco · YSL — pending recent
  {
    id: "sp-3" as Sample["id"],
    clientId: "cl-beatriz" as ClientId,
    baId: BA_POL_YSL_1,
    storeId: ST_POL,
    brand: "YSL",
    sku: "YS-LIB-1" as Sku,
    name: "Libre EDP · 1.2ml",
    givenAt: "2026-05-04T17:00:00.000Z",
    followUpAt: "2026-05-18T00:00:00.000Z",
    converted: false,
  },
  // Perisur · Lancôme — converted (linked to pu-5)
  {
    id: "sp-4" as Sample["id"],
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    storeId: ST_PER,
    brand: "Lancôme",
    sku: "LC-ABS-5" as Sku,
    name: "Absolue crema · 5ml",
    givenAt: "2026-04-18T11:30:00.000Z",
    converted: true,
    purchaseId: "pu-5" as Purchase["id"],
  },
  // Perisur · YSL — overdue, no conversion
  {
    id: "sp-5" as Sample["id"],
    clientId: "cl-gabriela" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    brand: "YSL",
    sku: "YS-OR-5" as Sku,
    name: "Or Rouge · 5ml",
    givenAt: "2026-03-22T15:00:00.000Z",
    followUpAt: "2026-04-05T00:00:00.000Z",
    converted: false,
  },
  // Perisur · YSL — recent pending
  {
    id: "sp-6" as Sample["id"],
    clientId: "cl-julieta" as ClientId,
    baId: BA_PER_YSL_2,
    storeId: ST_PER,
    brand: "YSL",
    sku: "YS-BO-1" as Sku,
    name: "Black Opium · 1.2ml",
    givenAt: "2026-05-08T12:30:00.000Z",
    followUpAt: "2026-05-22T00:00:00.000Z",
    converted: false,
  },
  // Santa Fe · Lancôme — converted (linked to pu-9)
  {
    id: "sp-7" as Sample["id"],
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_LCM_1,
    storeId: ST_STF,
    brand: "Lancôme",
    sku: "LC-REN-5" as Sku,
    name: "Rénergie H.C.F. · 5ml",
    givenAt: "2026-04-20T14:00:00.000Z",
    converted: true,
    purchaseId: "pu-9" as Purchase["id"],
  },
  // Santa Fe · Lancôme — recent pending
  {
    id: "sp-8" as Sample["id"],
    clientId: "cl-pamela" as ClientId,
    baId: BA_STF_LCM_1,
    storeId: ST_STF,
    brand: "Lancôme",
    sku: "LC-ABS-5" as Sku,
    name: "Absolue crema · 5ml",
    givenAt: "2026-05-07T13:00:00.000Z",
    followUpAt: "2026-05-21T00:00:00.000Z",
    converted: false,
  },
  // Santa Fe · YSL — overdue
  {
    id: "sp-9" as Sample["id"],
    clientId: "cl-rocio" as ClientId,
    baId: BA_STF_YSL_2,
    storeId: ST_STF,
    brand: "YSL",
    sku: "YS-LIB-1" as Sku,
    name: "Libre EDP · 1.2ml",
    givenAt: "2026-01-15T15:00:00.000Z",
    followUpAt: "2026-01-29T00:00:00.000Z",
    converted: false,
  },
  // ── Muestras YSL del catálogo expandido — recientes pending feedback ────
  {
    id: "sp-10" as Sample["id"],
    clientId: "cl-julieta" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    brand: "YSL",
    sku: "YS-PSE-3" as Sku,
    name: "Pure Shots Y-Shape Eye · 3ml",
    givenAt: "2026-05-09T16:00:00.000Z",
    followUpAt: "2026-05-23T00:00:00.000Z",
    converted: false,
  },
  {
    id: "sp-11" as Sample["id"],
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_YSL_2,
    storeId: ST_STF,
    brand: "YSL",
    sku: "YS-Y-1" as Sku,
    name: "Y EDP Hombre · 1.2ml",
    givenAt: "2026-04-29T19:00:00.000Z",
    converted: true,
    purchaseId: "pu-19" as Purchase["id"],
  },
  {
    id: "sp-12" as Sample["id"],
    clientId: "cl-pamela" as ClientId,
    baId: BA_STF_LCM_1, // BA Lancôme pero clientela multi-marca conoce YSL
    storeId: ST_STF,
    brand: "YSL",
    sku: "YS-MYS-1" as Sku,
    name: "MYSLF Hombre · 1.2ml",
    givenAt: "2026-05-06T14:00:00.000Z",
    followUpAt: "2026-05-20T00:00:00.000Z",
    converted: false,
  },

  // ── Muestras para nuevos clientes ──────────────────────────────────────
  {
    id: "sp-13" as Sample["id"],
    clientId: "cl-mariana-pol" as ClientId,
    baId: BA_POL_LCM_1,
    storeId: ST_POL,
    brand: "Lancôme",
    sku: "LC-HZN-7" as Sku,
    name: "Hydra Zen Gel Cream · 7ml",
    givenAt: "2026-04-08T15:30:00.000Z",
    followUpAt: "2026-04-22T00:00:00.000Z",
    converted: false,
  },
  {
    id: "sp-14" as Sample["id"],
    clientId: "cl-paloma-pol" as ClientId,
    baId: BA_POL_YSL_2,
    storeId: ST_POL,
    brand: "YSL",
    sku: "YS-LIB-1" as Sku,
    name: "Libre EDP · 1.2ml",
    givenAt: "2026-04-19T14:30:00.000Z",
    converted: true,
    purchaseId: "pu-21" as Purchase["id"],
  },
  {
    id: "sp-15" as Sample["id"],
    clientId: "cl-andrea-pol" as ClientId,
    baId: BA_POL_LCM_2,
    storeId: ST_POL,
    brand: "Lancôme",
    sku: "LC-REN-5" as Sku,
    name: "Rénergie H.C.F. · 5ml",
    givenAt: "2026-04-02T13:00:00.000Z",
    converted: true,
    purchaseId: "pu-23" as Purchase["id"],
  },
  {
    id: "sp-16" as Sample["id"],
    clientId: "cl-monica-pol" as ClientId,
    baId: BA_POL_YSL_2,
    storeId: ST_POL,
    brand: "YSL",
    sku: "YS-Y-1" as Sku,
    name: "Y EDP Hombre · 1.2ml",
    givenAt: "2026-05-09T15:00:00.000Z",
    followUpAt: "2026-05-23T00:00:00.000Z",
    converted: false,
  },
  {
    id: "sp-17" as Sample["id"],
    clientId: "cl-natalia-per" as ClientId,
    baId: BA_PER_LCM_2,
    storeId: ST_PER,
    brand: "Lancôme",
    sku: "LC-GEN-7" as Sku,
    name: "Advanced Génifique · 7ml",
    givenAt: "2026-05-02T13:30:00.000Z",
    converted: true,
    purchaseId: "pu-24" as Purchase["id"],
  },
  {
    id: "sp-18" as Sample["id"],
    clientId: "cl-yolanda-per" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    brand: "YSL",
    sku: "YS-OR-5" as Sku,
    name: "Or Rouge sérum · 5ml",
    givenAt: "2026-04-30T15:30:00.000Z",
    converted: true,
    purchaseId: "pu-25" as Purchase["id"],
  },
  {
    id: "sp-19" as Sample["id"],
    clientId: "cl-sandra-per" as ClientId,
    baId: BA_PER_YSL_2,
    storeId: ST_PER,
    brand: "YSL",
    sku: "YS-BO-1" as Sku,
    name: "Black Opium · 1.2ml",
    givenAt: "2026-05-10T16:00:00.000Z",
    followUpAt: "2026-05-24T00:00:00.000Z",
    converted: false,
  },
  {
    id: "sp-20" as Sample["id"],
    clientId: "cl-laura-stf" as ClientId,
    baId: BA_STF_LCM_2,
    storeId: ST_STF,
    brand: "Lancôme",
    sku: "LC-AEC-3" as Sku,
    name: "Absolue Eye Cream · 3ml",
    givenAt: "2026-04-27T14:30:00.000Z",
    converted: true,
    purchaseId: "pu-28" as Purchase["id"],
  },
  {
    id: "sp-21" as Sample["id"],
    clientId: "cl-bertha-stf" as ClientId,
    baId: BA_STF_YSL_2,
    storeId: ST_STF,
    brand: "YSL",
    sku: "YS-PSE-3" as Sku,
    name: "Pure Shots Y-Shape Eye · 3ml",
    givenAt: "2026-05-08T17:00:00.000Z",
    followUpAt: "2026-05-22T00:00:00.000Z",
    converted: false,
  },
  {
    id: "sp-22" as Sample["id"],
    clientId: "cl-tatiana-stf" as ClientId,
    baId: BA_STF_YSL_1,
    storeId: ST_STF,
    brand: "YSL",
    sku: "YS-MYS-1" as Sku,
    name: "MYSLF · 1.2ml",
    givenAt: "2026-05-04T13:30:00.000Z",
    followUpAt: "2026-05-18T00:00:00.000Z",
    converted: false,
  },
];

export const SEED_RECOMMENDATIONS: Recommendation[] = [
  // Polanco
  {
    id: "rc-1" as Recommendation["id"],
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    storeId: ST_POL,
    brand: "Lancôme",
    at: "2026-04-21T18:00:00.000Z",
    items: ["LC-ABS-50" as Sku, "LC-GEN-50" as Sku],
    status: "converted",
    purchaseId: "pu-1" as Purchase["id"],
  },
  {
    id: "rc-2" as Recommendation["id"],
    clientId: "cl-adriana" as ClientId,
    baId: BA_POL_YSL_2,
    storeId: ST_POL,
    brand: "YSL",
    at: "2026-03-18T15:30:00.000Z",
    items: ["YS-LIB-90" as Sku],
    status: "converted",
    purchaseId: "pu-4" as Purchase["id"],
  },
  // Perisur
  {
    id: "rc-3" as Recommendation["id"],
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    storeId: ST_PER,
    brand: "Lancôme",
    at: "2026-04-25T16:30:00.000Z",
    items: ["LC-ABS-50" as Sku],
    status: "converted",
    purchaseId: "pu-5" as Purchase["id"],
  },
  {
    id: "rc-4" as Recommendation["id"],
    clientId: "cl-gabriela" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    brand: "YSL",
    at: "2026-03-09T15:10:00.000Z",
    items: ["YS-RPC-01" as Sku],
    status: "pending",
  },
  // Santa Fe
  {
    id: "rc-5" as Recommendation["id"],
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_LCM_1,
    storeId: ST_STF,
    brand: "Lancôme",
    at: "2026-04-28T16:00:00.000Z",
    items: ["LC-ABS-50" as Sku, "LC-HZN-50" as Sku],
    status: "converted",
    purchaseId: "pu-9" as Purchase["id"],
  },
  {
    id: "rc-6" as Recommendation["id"],
    clientId: "cl-nadia" as ClientId,
    baId: BA_STF_YSL_1,
    storeId: ST_STF,
    brand: "YSL",
    at: "2025-12-09T11:30:00.000Z",
    items: ["YS-RPC-01" as Sku],
    status: "pending",
  },
  // ── YSL recos del catálogo expandido ──────────────────────────────────
  {
    id: "rc-7" as Recommendation["id"],
    clientId: "cl-rocio" as ClientId,
    baId: BA_STF_YSL_1,
    storeId: ST_STF,
    brand: "YSL",
    at: "2026-04-15T17:00:00.000Z",
    items: ["YS-BO-50" as Sku, "YS-TC-01" as Sku],
    status: "converted",
    purchaseId: "pu-17" as Purchase["id"],
  },
  {
    id: "rc-8" as Recommendation["id"],
    clientId: "cl-gabriela" as ClientId,
    baId: BA_PER_YSL_2,
    storeId: ST_PER,
    brand: "YSL",
    at: "2026-04-22T15:30:00.000Z",
    items: ["YS-PSE-15" as Sku, "YS-LC-01" as Sku],
    status: "converted",
    purchaseId: "pu-18" as Purchase["id"],
  },

  // ── Recos para nuevos clientes — más conversiones para reportes ────────
  {
    id: "rc-9" as Recommendation["id"],
    clientId: "cl-andrea-pol" as ClientId,
    baId: BA_POL_LCM_2,
    storeId: ST_POL,
    brand: "Lancôme",
    at: "2026-04-02T13:30:00.000Z",
    items: ["LC-REN-50" as Sku, "LC-ABS-50" as Sku],
    status: "pending",
  },
  {
    id: "rc-10" as Recommendation["id"],
    clientId: "cl-paloma-pol" as ClientId,
    baId: BA_POL_YSL_2,
    storeId: ST_POL,
    brand: "YSL",
    at: "2026-04-19T14:45:00.000Z",
    items: ["YS-LIB-90" as Sku, "YS-TC-01" as Sku],
    status: "converted",
    purchaseId: "pu-21" as Purchase["id"],
  },
  {
    id: "rc-11" as Recommendation["id"],
    clientId: "cl-natalia-per" as ClientId,
    baId: BA_PER_LCM_2,
    storeId: ST_PER,
    brand: "Lancôme",
    at: "2026-05-02T14:00:00.000Z",
    items: ["LC-REN-50" as Sku, "LC-ABS-50" as Sku],
    status: "converted",
    purchaseId: "pu-24" as Purchase["id"],
  },
  {
    id: "rc-12" as Recommendation["id"],
    clientId: "cl-yolanda-per" as ClientId,
    baId: BA_PER_YSL_1,
    storeId: ST_PER,
    brand: "YSL",
    at: "2026-04-30T15:30:00.000Z",
    items: ["YS-OR-100" as Sku, "YS-PSE-15" as Sku],
    status: "converted",
    purchaseId: "pu-25" as Purchase["id"],
  },
  {
    id: "rc-13" as Recommendation["id"],
    clientId: "cl-laura-stf" as ClientId,
    baId: BA_STF_LCM_2,
    storeId: ST_STF,
    brand: "Lancôme",
    at: "2026-04-27T15:00:00.000Z",
    items: ["LC-ABS-50" as Sku, "LC-AEC-20" as Sku],
    status: "converted",
    purchaseId: "pu-28" as Purchase["id"],
  },
  {
    id: "rc-14" as Recommendation["id"],
    clientId: "cl-bertha-stf" as ClientId,
    baId: BA_STF_YSL_2,
    storeId: ST_STF,
    brand: "YSL",
    at: "2026-05-01T17:30:00.000Z",
    items: ["YS-OR-100" as Sku, "YS-BO-50" as Sku],
    status: "converted",
    purchaseId: "pu-29" as Purchase["id"],
  },
];

export const SEED_COMMUNICATIONS: Communication[] = [
  // ── Polanco ───────────────────────────────────────────────────────────────
  {
    id: "cm-1" as CommunicationId,
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    brand: "Lancôme",
    storeId: ST_POL,
    channel: "WhatsApp",
    direction: "outbound",
    at: "2026-04-22T14:32:00.000Z",
    templateId: "tpl-postvisit-es",
    body: "Hola Constanza, ¿cómo te sentiste con el sérum Génifique?",
    status: "read",
  },
  {
    id: "cm-2" as CommunicationId,
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_LCM_1,
    brand: "Lancôme",
    storeId: ST_POL,
    channel: "WhatsApp",
    direction: "inbound",
    at: "2026-04-22T18:04:00.000Z",
    body: "¡Increíble, notó mi marido el brillo!",
    status: "read",
  },
  {
    id: "cm-3" as CommunicationId,
    clientId: "cl-constanza" as ClientId,
    baId: BA_POL_YSL_1,
    brand: "YSL",
    storeId: ST_POL,
    channel: "Email",
    direction: "outbound",
    at: "2026-03-13T09:00:00.000Z",
    templateId: "tpl-launch-es",
    body: "Hola Constanza, la nueva Libre Le Parfum acaba de llegar.",
    status: "delivered",
  },
  {
    id: "cm-4" as CommunicationId,
    clientId: "cl-ofelia" as ClientId,
    baId: BA_POL_LCM_2,
    brand: "Lancôme",
    storeId: ST_POL,
    channel: "SMS",
    direction: "outbound",
    at: "2026-04-20T11:00:00.000Z",
    templateId: "tpl-replenish-es",
    body: "Tu Hydrating Boost está por terminarse…",
    status: "read",
  },

  // ── Perisur ───────────────────────────────────────────────────────────────
  {
    id: "cm-5" as CommunicationId,
    clientId: "cl-gabriela" as ClientId,
    baId: BA_PER_YSL_1,
    brand: "YSL",
    storeId: ST_PER,
    channel: "WhatsApp",
    direction: "outbound",
    at: "2026-04-15T10:00:00.000Z",
    templateId: "tpl-launch-es",
    body: "Gabriela, acaba de llegar Libre Le Parfum Intense.",
    status: "delivered",
  },
  {
    id: "cm-6" as CommunicationId,
    clientId: "cl-cristina" as ClientId,
    baId: BA_PER_LCM_1,
    brand: "Lancôme",
    storeId: ST_PER,
    channel: "Email",
    direction: "outbound",
    at: "2026-04-26T10:30:00.000Z",
    templateId: "tpl-postvisit-es",
    body: "Cristina, qué bueno verte. Gracias por tu compra.",
    status: "read",
  },
  {
    id: "cm-7" as CommunicationId,
    clientId: "cl-julieta" as ClientId,
    baId: BA_PER_YSL_1,
    brand: "YSL",
    storeId: ST_PER,
    channel: "WhatsApp",
    direction: "outbound",
    at: "2026-03-01T13:00:00.000Z",
    body: "Te envío la rutina sensible que platicamos.",
    status: "read",
  },

  // ── Santa Fe ──────────────────────────────────────────────────────────────
  {
    id: "cm-8" as CommunicationId,
    clientId: "cl-marina" as ClientId,
    baId: BA_STF_LCM_1,
    brand: "Lancôme",
    storeId: ST_STF,
    channel: "WhatsApp",
    direction: "outbound",
    at: "2026-04-19T09:30:00.000Z",
    templateId: "tpl-postvisit-es",
    body: "Marina, gracias por venir. Te mando link del sérum.",
    status: "read",
  },
  {
    id: "cm-9" as CommunicationId,
    clientId: "cl-karla" as ClientId,
    baId: BA_STF_LCM_1,
    brand: "Lancôme",
    storeId: ST_STF,
    channel: "Email",
    direction: "outbound",
    at: "2026-04-29T11:00:00.000Z",
    templateId: "tpl-anniversary-es",
    body: "Karla, queremos celebrar 7 años contigo.",
    status: "delivered",
  },
  {
    id: "cm-10" as CommunicationId,
    clientId: "cl-rocio" as ClientId,
    baId: BA_STF_YSL_2,
    brand: "YSL",
    storeId: ST_STF,
    channel: "SMS",
    direction: "outbound",
    at: "2026-02-01T10:00:00.000Z",
    templateId: "tpl-replenish-es",
    body: "Tu Libre está por terminarse. ¿Te lo aparto?",
    status: "delivered",
  },
];

export const SEED_CONSENTS: Consent[] = [
  {
    id: "co-1" as Consent["id"],
    clientId: "cl-constanza" as ClientId,
    channel: "WhatsApp",
    status: "granted",
    at: "2025-10-01T00:00:00.000Z",
    version: "v2026.03",
    source: "in-store",
  },
  {
    id: "co-2" as Consent["id"],
    clientId: "cl-constanza" as ClientId,
    channel: "Email",
    status: "granted",
    at: "2025-10-01T00:00:00.000Z",
    version: "v2026.03",
    source: "in-store",
  },
];
